/**
 *  @file
 *  @brief       Rotor Flux Speed Position observer for PMSM motor
 *  @details     This module implements a rotor flux speed/position observer for a 3-phase PMSM motor.
 *               Fixed point implementation.
 *  @author      alessio.beato/luigi.fagnano  (only temporary, since it is not integrated in MKS)
 *  $Header: FOC/ObserverPmsm.h 1.4 2015/09/24 20:12:50CEST Luigi Fagnano (FAGNAL) Exp  $
 * @copyright Copyright 2012 - $Date: 2015/09/24 20:12:50CEST $. Whirlpool Corporation. All rights reserved – CONFIDENTIAL
*/


//-------------------------------------- Include Files ----------------------------------------------------------------
#include "ObserverPmsm.h"
#include "ClrkPark.h"
#include "MathCalc.h"
//-------------------------------------- PUBLIC (Variables) -----------------------------------------------------------

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
#define STARTUP_OBSERVER_MIN_SPEED      MC_FLOAT_TO_IQ15S(0.0025f)    //50 rpm on 19800 rpm base

#ifndef PI
    #define PI 3.1415926535897932384626433832795f
#endif
//-------------------------------------- PRIVATE (Function Prototypes) ------------------------------------------------


//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================

//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      It Initializes the module BemfObserver and its variables
 *
 */
void ObserverPmsm__Initialize(void)
{
        /* TO DO: initialization of parameters from setting file */
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Back-EMF observer for PMSM motor.
 *  @details
 *
 * That observer estimates the D-Q components of back-emf generated by the permanent magnet flux on the stator windings according to the following equations:
 *
 *
 * \f[
 *  \begin{aligned}
 *     &\frac{\hat{dI_{d}}(t)}{dt}  =  -\frac{R}{L_{d}}\cdot {\hat{I}_{d}(t)} +\frac{1}{L_{d}}\cdot {\hat{E}_{d}(t)} + \frac{1}{L_{d}}\cdot {(V_{sd}(t)+ L_{q}w_{el}{I}_{q}(t))}\\
 *     &\frac{\hat{dI_{q}}(t)}{dt}  =  -\frac{R}{L_{d}}\cdot {\hat{I}_{q}(t)} +\frac{1}{L_{d}}\cdot {\hat{E}_{q}(t)} + \frac{1}{L_{d}}\cdot {(V_{sq}(t)- L_{q}w_{el}{I}_{d}(t))}\\
 *     &\frac{\hat{dE_{d}}(t)}{dt}  =  K_{i}\cdot {(I_{d}(t) - \hat{I}_{d}(t))} +K_{p}\cdot {(\frac{dI_{d}(t)}{dt} - \frac{\hat{dI_{d}}(t)}{dt})} \\
 *       &\frac{\hat{dE_{q}}(t)}{dt}  =  K_{i}\cdot {(I_{q}(t) - \hat{I}_{q}(t))} +K_{p}\cdot {(\frac{dI_{q}(t)}{dt} - \frac{\hat{dI_{q}}(t)}{dt})} \\
 *  \end{aligned}
 * \f]
 *
 * where
 *
 * \f$ V_{d} \f$: voltage on d axis
 *
 * \f$ V_{q} \f$: voltage on q axis
 *
 * \f$ I_{d} \f$: current on d axis
 *
 * \f$ I_{q} \f$: current on q axis
 *
 * \f$ \hat{I_{d}} \f$: estimated current on d axis
 *
 * \f$ \hat{I_{q}} \f$: estimated current on q axis
 *
 * \f$ \hat{E_{d}} \f$: estimated back-emf on d axis
 *
 * \f$ \hat{E_{q}} \f$: estimated back-emf on q axis
 *
 * \f$ w_{el} \f$: rotor flux speed
 *
 * The observer model uses the back-emf extended formula
 *
 *
 * \f[
 *  \begin{aligned}
 *     &E_{d}(t) = 0 \\
 *     &E_{q}(t) = E_{a} = {(L_{q}-L_{d})}\cdot \frac{{dI_{q}}(t)}{dt} +   {(L_{d}-L_{q})}\cdot {w_{el}I_{d}}  + w_{el}\cdot{Phi_{m}}\\
 *  \end{aligned}
 * \f]
 *
 *
 * The estimated back-emf depend on the d-q position estimation error
 *
 * \f[
 *  \begin{aligned}
 *     &\hat{E_{d}}(t) =  E_{a}\cdot{sin(Theta_{Err})} \\
 *     &\hat{E_{q}}(t) =  -E_{a}\cdot{cos(Theta_{Err})}\\
 *  \end{aligned}
 * \f]
 *
 * Tha estimated back-emfs are used to calculate the position estimation error.
 *
 * \f[
 *  \begin{aligned}
 *     &Theta_{Err} = atan(\frac{\hat{E}_{d}(t)}{-\hat{E_{q}}(t)}) =  atan(\frac{E_{a}\cdot{sin(Theta_{Err})}}{E_{a}\cdot{cos(Theta_{Err})}})  \\
 *  \end{aligned}
 * \f]
 *

 * Discretizing the previous equations using backward Euler transformation:
 *
 * \f[
 *  \begin{aligned}
 *     & IntegralStateD(k) =  Ki*Ts\cdot{(I_{d}(k) - \hat{I}_{d}(k-1))}  +  IntegralStateD(k-1)\\
 *     &\hat{E_{d}}(k)  =  (Kp\cdot{(I_{d}(k) - \hat{I}_{d}(k-1))}  +  IntegralStateD(k))\\
 *     &\hat{I_{d}}(k)  =  (Ld/(Ld+Ts\cdot{Rs}))\cdot {\hat{I}_{d}(k-1)}  +  (Ts/(Ld+Ts\cdot{Rs}))\cdot {E_{d}(k)} + (Ts/(Ld+Ts\cdot{Rs}))\cdot {V_{d}(k)}  +  (Ts\cdot{Lq}/(Ld+Ts\cdot{Rs}))\cdot {L_{q}w_{el}(k){I}_{q}(k)} \\
 *     & IntegralStateQ(k) =  Ki*Ts\cdot{(I_{d}(k) - \hat{I}_{d}(k-1))}  +  IntegralStateQ(k-1)\\
 *     &\hat{E_{q}}(k)  =  (Kp\cdot{(I_{q}(k) - \hat{I}_{q}(k-1))}  +  IntegralStateQ(k))\\
 *     &\hat{I_{d}}(k)  =  (Ld/(Ld+Ts\cdot{Rs}))\cdot {\hat{I}_{q}(k-1)}  +  (Ts/(Ld+Ts\cdot{Rs}))\cdot {E_{q}(k)} + (Ts/(Ld+Ts\cdot{Rs}))\cdot {V_{d}(k)}  -  (Ts\cdot{Lq}/(Ld+Ts\cdot{Rs}))\cdot {L_{q}w_{el}(k){I}_{q}(k)} \\
 *  \end{aligned}
 * \f]
 *
 * where
 *
 * Ts is the sampling period
 *
 *  @param[in]      i_dq   = motor current components in d-q reference frame (aligned with rotor flux position)
 *  @param[in]      v_dq   = motor voltage components in d-q reference frame (aligned with rotor flux position)
 *  @param[in]      OmegaFlux   = rotor electrical speed in Q17.15 notation
 *  @param[in,out]      params = this structure contains parameters used for back-emf equation, rotor-flux position, PI gains, estimated quantities [current/bemf]
 */
void ObserverPmsm__BemfObsDQ(DQ_COOR_SYST_TYPE* i_dq, DQ_COOR_SYST_TYPE* v_dq, mc_sint32 omega_flux, BEMF_OBSERVER_PARAMS_TYPE* params)
{

    mc_sint32 id_error;
    mc_sint32 iq_error;
    mc_sint32 bemf_d_15;
    mc_sint32 bemf_q_15;
    mc_sint64 temp64;

    //------------------------------------------------------------------------
    //               Calculation params.BemfEst.D
    // ------------------------------------------------------------------------
    id_error = i_dq->D - MC_SCALE(params->Current_Est.D,IQ30,IQ15);

    params->Bemf_Est.D =    Pi__PiRegNoAntiWindup(id_error, &params->Pi_States.State_D, &params->Pi_Parameters);

    // ------------------------------------------------------------------------
    //               Calculation params.CurrentEst.D
    // ------------------------------------------------------------------------
    //params->CurrentEst.D = params->Icoeff*params->CurrentEst.D    +    params->Ecoeff*params->BemfEst.D  +  params->Ucoeff*v_dq->D     + params->WIcoeff*w_el*i_dq->Q;
    //temp64 = (sint64)IQMATH__I2Q30MULI17Q15_I2Q30(params->Icoeff, params->CurrentEst.D);
    temp64 = MC_MULT_LL_LL(params->I_Coeff, params->Current_Est.D, IQ15, IQ30, IQ30);
    temp64 = temp64 + MC_MULT_LL_LL(params->E_Coeff, params->Bemf_Est.D,IQ14,IQ30,IQ30);
    temp64 = temp64 + (mc_sint64)params->U_Coeff * (mc_sint64)v_dq->D;
    temp64 = temp64 + MC_MULT_LL_LL(params->WI_Coeff, ((mc_sint64)omega_flux * (mc_sint64)i_dq->Q), IQ14, IQ30, IQ30);

    //saturation
    if (temp64 > (mc_sint64)MC_ONE_IQ30)
    {
        params->Current_Est.D = MC_ONE_IQ30;
    }
    else if (temp64 < (mc_sint64)MC_MINUS_ONE_IQ30)
    {
        params->Current_Est.D = MC_MINUS_ONE_IQ30;
    }
    else
    {
        params->Current_Est.D = (mc_sint32)temp64;
    }



    // ------------------------------------------------------------------------
    //               Calculation params.BemfEst.Q
    // ------------------------------------------------------------------------
    iq_error = i_dq->Q - MC_SCALE(params->Current_Est.Q,IQ30, IQ15);

    params->Bemf_Est.Q =    Pi__PiRegNoAntiWindup(iq_error, &params->Pi_States.State_Q, &params->Pi_Parameters);


    //------------------------------------------------------------------------
    //               Calculation params.CurrentEst.Q
    // ------------------------------------------------------------------------
    //params->CurrentEst.Q = params->Icoeff*params->CurrentEst.Q    +    params->Ecoeff*params->BemfEst.Q +   params->Ucoeff*v_dq->Q     - params->WIcoeff*w_el*i_dq->D;
    //temp64 = (sint64)IQMATH__I2Q30MULI17Q15_I2Q30(params->Icoeff, params->CurrentEst.Q);
    temp64 = MC_MULT_LL_LL(params->I_Coeff, params->Current_Est.Q, IQ15, IQ30, IQ30);
    temp64 = temp64 + MC_MULT_LL_LL(params->E_Coeff, params->Bemf_Est.Q,IQ14, IQ30, IQ30);
    temp64 = temp64 + (mc_sint64)params->U_Coeff *(mc_sint64)v_dq->Q;
    temp64 = temp64 - MC_MULT_LL_LL(params->WI_Coeff, ((mc_sint64)omega_flux * (mc_sint64)i_dq->D),IQ14, IQ30, IQ30);

    //saturation
    if (temp64 > (mc_sint64)MC_ONE_IQ30)
    {
        params->Current_Est.Q = MC_MINUS_ONE_IQ30;
    }
    else if (temp64 < (mc_sint64)MC_MINUS_ONE_IQ30)
    {
        params->Current_Est.Q = MC_MINUS_ONE_IQ30;
    }
    else
    {
        params->Current_Est.Q = (mc_sint32)temp64;
    }



    //Position Error calculation
    bemf_d_15 = MC_SCALE(params->Bemf_Est.D,IQ30,IQ15);   //17.15 = 2.30>>15
    bemf_q_15 = MC_SCALE(params->Bemf_Est.Q,IQ30,IQ15);     //17.15 = 2.30>>15

    params->Theta_Flux_Error = (mc_sint16)MC_ATAN2(-bemf_q_15, bemf_d_15);

}



//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Tracking observer for PMSM motor.
 *  @details
 *
 * This module estimates the rotor flux speed and position starting from the position error calculated by the bemf observer according to the following equations:
 *
 *
 * \f[
 *  \begin{aligned}
 *     & \hat{\omega}(t) = \frac{\hat{d\theta}(t)}{dt} = K_{p}\cdot {\theta_{err}}  +  K_{i}\cdot {\int{\theta_{err}\cdot{dt}}}\\
 *     & \hat{\theta}(t) = {\int{\hat{\omega}(t)\cdot{dt}}}\\
 *  \end{aligned}
 * \f]
 *
 * where
 *
 * \f$ \hat{\omega}(t) \f$: estimated rotor flux speed
 *
 * \f$ \hat{\theta}(t) \f$: estimated rotor flux position
 *
 * \f$ \hat{\theta}_{err}(t) \f$: rotor flux estimated position error
 *
 * Discretizing the previous equations using backward Euler transformation:
 *
 * \f[
 *  \begin{aligned}
 *     & IntegralState(k) =  Ki*Ts\cdot{\theta_{err}(k)}  +  IntegralState(k-1)\\
 *     &\hat{\omega}(k) =  Kp\cdot{\theta_{err}(k)}  +  IntegralState(k)\\
 *     &\hat{\theta}(k) =  \hat{\theta}(k-1)  +  Ts\cdot {\omega}(k)\\
 *  \end{aligned}
 * \f]
 *
 * where
 *
 * Ts is the sampling period
 *
 *
 *  @param[in]      theta_err  = position estimation error in Q1.15 notation
 *  @param[in,out]  params = this structure contains parameters used for PI gains, estimated speed and position
 *  @return            theta_inj_short   = estimated position in Q1.15 notation
 */
mc_sint16 ObserverPmsm__TrackingObs(mc_sint16 theta_err, TRACKING_OBSERVER_PARAMS_TYPE *params)
{
    mc_sint32 temp32;
    mc_sint16 theta_inj_short;

    //Pi Execution -> Speed estimation
    params->Omega_Est =    Pi__PiRegNoAntiWindup((mc_sint32)theta_err, &params->State_PI, &params->Pi_Parameters);

    temp32 = MC_SCALE(params->Omega_Est,IQ30,IQ15); //17.15 = 2.30>>15

    //Angle update according the estimated speed
    theta_inj_short = (mc_sint16)Pi__IntegBE(temp32, &params->Theta_Est, &params->Integ_Parameters); // Thet_inj = Theta_inj_k + Ts*2*pi*SpeedEst

    return theta_inj_short;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 *  @brief      Startup observer for PMSM motor.
 *  @details
 *
 * That observer estimates two electrical speeds according to the following equations:
 *
 *
 * \f[
 *  \begin{aligned}
 *     &\hat{\omega_d} = V_d \cdot \left[-\frac{1}{L_s I_q}\right]\\
 *     &\hat{\omega_d} = (V_q - V_{qAlign}) \cdot \frac{1}{\varphi_m}\\
 *  \end{aligned}
 * \f]
 *
 * where
 *
 * \f$ V_{d} \f$: voltage on d axis
 *
 * \f$ V_{q} \f$: voltage on q axis
 *
 * \f$ I_{q} \f$: current on q axis
 *
 * \f$ \hat{omega_{d}} \f$: estimated speed based on d axis equation
 *
 * \f$ \hat{omega_{q}} \f$: estimated speed based on q axis equation
 *
 * \f$ -\left[\frac{1}{L_s I_q}\right] = K1 \f$
 *
 * \f$ \frac{1}{\varphi_m} = K2 \f$
 *
 * The error is given by:
 *
 * \f$ \omega_{error} = \hat{\omega_{d}} - \hat{\omega_{q}} \f$
 *
 *
 *
 *  @param[in]      v_dq   = motor voltage components in d-q reference frame (aligned with rotor flux position)
 *  @param[in,out]  omega_startup  = estimated motor electrical speed (d and q equations)
 *  @param[in]      vq_alignment   = measured voltage during alignment phase (equal to \f$ R_s I_q \f$ )
 *  @param[in]      params = this structure contains parameters used for startup observer K1, K2
 *  @return         error  = \f$ \hat{\omega_{d}} - \hat{\omega_{q}} \f$
 */
mc_sint32 ObserverPmsm__StartupObs(DQ_COOR_SYST_TYPE* v_dq, mc_sint32 vq_alignment, STARTUP_OBSERVER_PARAMS_TYPE* params)
{
    mc_sint32 temp;
    mc_sint32 error;
    DQ_COOR_SYST_TYPE v_dq_sobs;
    ALPHA_BETA_COOR_SYST_TYPE v_alphabeta_sobs;
    mc_sint32 theta_est;
    SIN_COS_TYPE    sin_cos_theta_flux;


    // calculation of Vs d-q components on estimated position by startup observer
    theta_est = MC_SCALE(params->Theta_Est_Q, IQ30, IQ15);

    MC_SINCOS(theta_est, &sin_cos_theta_flux);

    ClrkPark__InversePark(v_dq, &v_alphabeta_sobs, &sin_cos_theta_flux);

    theta_est = MC_SCALE(params->Theta_Est, IQ30, IQ15);

    MC_SINCOS(theta_est, &sin_cos_theta_flux);

    ClrkPark__DirectPark(&v_alphabeta_sobs, &v_dq_sobs, &sin_cos_theta_flux);




    // Startup observer equation

    // Omega d-calculation
    params->Omega_Est_D = MC_MULT_L(v_dq_sobs.D,params->K_1, IQ15, IQ15, IQ15);  //w_d = Vd/(Lq*CurrentStartup)

    // Omega q-calculation
    temp = v_dq_sobs.Q - vq_alignment;
    params->Omega_Est_Q = MC_MULT_L(temp, params->K_2, IQ15, IQ15, IQ15);       //w_q = (Vq - Rs*CurrentStartup)/(Phim)


    // angle estimation angle calculation
    error = params->Omega_Est_D - params->Omega_Est_Q;


    if(params->Omega_Est_D > STARTUP_OBSERVER_MIN_SPEED)
    {
        error = MathCalc__Arctan2(params->Omega_Est_D,error);
    }

    // Pi execution to reduce the error angle
    params->Omega_Est = Pi__PiRegBackCalc(error, &params->State_PI, &params->Pi_Parameters);


    //Angle update according the estimated speed
    theta_est = (mc_sint16)Pi__IntegBE(params->Omega_Est, &params->Theta_Est, &params->Integ_Parameters); // Thet_inj = Theta_inj_k + Ts*2*pi*SpeedEst

    //Angle update according the estimated speed
    theta_est = (mc_sint16)Pi__IntegBE(params->Omega_Est_Q, &params->Theta_Est_Q, &params->Integ_Parameters); // Thet_inj = Theta_inj_k + Ts*2*pi*SpeedEst


    return theta_est;

}


void ObserverPmsm__BemfObsDQF(DQ_COOR_SYST_F_TYPE* i_dq, DQ_COOR_SYST_F_TYPE* v_dq, float32 omega_flux, BEMF_OBSERVER_PARAMS_F_TYPE* params)
{
    float32 temp;

    //------------------------------------------------------------------------
    //               Calculation params.BemfEst.D
    // ------------------------------------------------------------------------
    params->Pi_D.Err = i_dq->D - params->Current_Est.D;
    Pi__PiRegNoAntiWindupF(&params->Pi_D);
    params->Bemf_Est.D = params->Pi_D.Out;

    // ------------------------------------------------------------------------
    //               Calculation params.CurrentEst.D
    // ------------------------------------------------------------------------
    temp = params->I_Coeff * params->Current_Est.D;
    temp = temp + params->E_Coeff * params->Bemf_Est.D;
    temp = temp + params->U_Coeff * v_dq->D;
    temp = temp + params->WI_Coeff * (omega_flux * i_dq->Q);

    params->Current_Est.D = temp;



    // ------------------------------------------------------------------------
    //               Calculation params.BemfEst.Q
    // ------------------------------------------------------------------------
    params->Pi_Q.Err = i_dq->Q - params->Current_Est.Q;
    Pi__PiRegNoAntiWindupF(&params->Pi_Q);
    params->Bemf_Est.Q = params->Pi_Q.Out;

    //------------------------------------------------------------------------
    //               Calculation params.CurrentEst.Q
    // ------------------------------------------------------------------------
    temp = params->I_Coeff * params->Current_Est.Q;
    temp = temp + (params->E_Coeff * params->Bemf_Est.Q);
    temp = temp + (params->U_Coeff * v_dq->Q);
    temp = temp - (params->WI_Coeff * (omega_flux * i_dq->D));

    params->Current_Est.Q = temp;

    //Position Error calculation
    params->Theta_Flux_Error = MathCalc__Arctan2F(-(params->Bemf_Est.Q), params->Bemf_Est.D);
}

float32 ObserverPmsm__TrackingObsF(float32 theta_err, TRACKING_OBSERVER_PARAMS_F_TYPE *params)
{
    //Pi Execution -> Speed estimation
    params->Pi.Err = theta_err;
    Pi__PiRegNoAntiWindupF(&params->Pi);
    params->Omega_Est = params->Pi.Out;

    //Angle update according the estimated speed
    params->Theta_Est = params->Theta_Est + params->Omega_Est * (params->Integ_Parameters.Ki); // Thet_inj = Theta_inj_k + Ts*SpeedEst

    if(params->Theta_Est > PI)
    {
        params->Theta_Est -= (2.0f * PI);
    }

    if(params->Theta_Est < (-PI))
    {
        params->Theta_Est += (2.0f * PI);
    }

    return params->Theta_Est;
}


float32 ObserverPmsm__StartupObsF(DQ_COOR_SYST_F_TYPE* v_dq, float32 vq_alignment, STARTUP_OBSERVER_PARAMS_F_TYPE* params)
{
    float32 temp;
    float32 error;
    DQ_COOR_SYST_F_TYPE v_dq_sobs;
    ALPHA_BETA_COOR_SYST_F_TYPE v_alphabeta_sobs;
    SIN_COS_F_TYPE    sin_cos_theta_flux;

    // calculation of Vs d-q components on estimated position by startup observer
    MC_SINCOS_F(params->Theta_Est_Q, &sin_cos_theta_flux);
    ClrkPark__InverseParkF(v_dq, &v_alphabeta_sobs, &sin_cos_theta_flux);

    MC_SINCOS_F(params->Theta_Est, &sin_cos_theta_flux);
    ClrkPark__DirectParkF(&v_alphabeta_sobs, &v_dq_sobs, &sin_cos_theta_flux);


    // Startup observer equation

    // Omega d-calculation
    params->Omega_Est_D = v_dq_sobs.D * params->K_1;  //w_d = Vd/(Lq*CurrentStartup)

    // Omega q-calculation
    temp = v_dq_sobs.Q - vq_alignment;
    params->Omega_Est_Q = temp * params->K_2;       //w_q = (Vq - Rs*CurrentStartup)/(Phim)

    // angle estimation angle calculation
    error = params->Omega_Est_D - params->Omega_Est_Q;

    // Pi execution to reduce the error angle
    params->Pi.Err = error;
    Pi__CalcPiBackCalcF(&params->Pi);
    params->Omega_Est = params->Pi.Out;

    //Angle update according the estimated speed
    params->Theta_Est = params->Theta_Est + params->Omega_Est * (params->Integ_Parameters.Ki); // Thet_inj = Theta_inj_k + Ts*SpeedEst

    //Angle update according the estimated speed
    params->Theta_Est_Q = params->Theta_Est_Q + params->Omega_Est_Q * (params->Integ_Parameters.Ki); // Thet_inj = Theta_inj_k + Ts*SpeedEst

    return params->Theta_Est_Q;
}
