/**
 *  @file        Mcl_Additional_prm.h
 *  @brief       DTC Loop Parameters for 3-phase motors.
 *
 *               ==== AUTOMATIC GENERATED FILE! DO NOT TOUCH IT, USE EXCEL MACRO! ====
 *
 *  @details     This module defines all parameters of the DTC control loop for 3-phase motors. Created in 11/6/2021 12:48 
 *               Setting File Parameters for sBPM Hefei H27
 *               Generated from https://docs.google.com/spreadsheets/d/16lyTsVAZrbepZVDuSsIOn90_8iekF4pqHCact2xnWpY/edit
 *               Generated by luigi_fagnano@whirlpool.com
 *  @copyright   Copyright 2021.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL
 *
 */

#ifndef MCL_COMPLETE_SBPM_PRM_H
#define MCL_COMPLETE_SBPM_PRM_H


//=====================================================================================================================
//-------------------------------------- PUBLIC (Extern Variables, Constants & Defines) -------------------------------
//=====================================================================================================================


#include "MciParametersLoader_prv.h"


//DTC Phisical Motor Control Parameters

//0.1
//Stator Resistance = 2.87 Ohm
//Rotor flux  = 0.0845 Wb
//Maximum electromagnetic torque = 4 Nm

//Pole pairs
//Current Offset Comp Speed Thr (0 to disable) = 0 rpm
//Current Offset Comp Speed Thr hysteresis = 0 %
//Current Offset Comp Current Thr = 0 A
//Current Offset Comp Max Current Compensation = 0 A
//Current Offset Comp Full Cycle Counter = 0 na

//Hardware (inverter) configuration
//Maximum peak phase current = 6 A

//Observer Parameters
//Stator Resistance adaptation limits = 15 %
//Stator Resistance adaptation gain = 160 Ohm/(Wb*s)
//Stator Resistance adaptation recovery = 83.33 Ohm*us
//Current threshold to enable resistance adaptation = 4.5 A
//Speed threshold to enable resistance adaptation = 40 rpm
//Observer G gain = 60 V/Wb
//Observer Integ G gain = 1000 V/Wb/s
//Observer Integ Limits = 0.5 V
//Observer Integ activation speed threshold = 400 rpm
//Stator Resistance adaptation offset = 0 Ohm
//Phase Advance Coefficient (0 to disable) = 0 NA
//Starting time threshold = 0.5 s
//PLL - Kp gain = 118 1/s
//PLL - Ki gain = 3410 Stat
//PLL - Engage Speed Threshold  = 40 rpm
//Observer call rate (sampling time) = 0.000125 s
//Swap Phase Time Activation Sample (0 to disable) = 0 s

//Speed Controller Parameters
//Maximum cosine of load angle = -0.26 NA
//Load angle controller Kp = 0 Nm
//Load angle controller Ki = 8000 Nm/s
//Time to force the use of default gains = 1 s
//Default Acceleration = 75 rpm/s
//Min Speed Default Acceleration = 15 rpm
//Max Braking Diss Torque = 1 Nm
//Max Braking  Diss Current = 3.38 A
//Min Braking Diss Torque = 0.1 Nm
//Min Braking Diss Torque Threshold = 80 %
//Max Braking Gen Low Speed = 0.2 Nm
//Max Braking Gen High Speed = 0 Nm
//Max Braking Gen Low/High Speed Threshold = 1900 rpm
//Braking Resistance Percentage = 95 %
//Id Braking Prop Gain  = 0.02 A
//Id Braking Step Back = 0.05 A
//Braking Mode = 0 NA

//DQ Reference Generator Parameters
//Starting time = 1 s
//Maximum designed flux  = 0.2 Wb
//Speed threshold to enable/disable overflux = 375 rpm
//Percentage to be applied of overflux = 10 %
//Overflux decrement = 0.0001 Wb
//Overflux Charging = 0.001 Wb
//Overflux min percentage = 0 %
//Overflux activation threshold  = 100 %
//Flux Adaptation G Gain (0 to disable) = 0.2 Wb/A*Ts
//FLux Adaptation Hysteresis Percentage = 30 %
//K (torque error compensation) = 0.58 1/Nm
//Torque error compensation saturation = 0.5 NA
//Max Modulation Index(REF) = 98 %

//DQ Controllers Parameters
//Starting time to force gains = 1 s
//Phase advance coefficient = 1 NA
//Max Modulation Index (CTRL) = 115 %
//Pi Volt Margin for Vd_Max = 140 V
//Absolute speed threshold range - region[0] = 1905 rpm
//Absolute speed threshold range - region[1] = 14000 rpm
//Absolute speed threshold range - region[2] = 20000 rpm
//Torque controller Kp - region [0] = 10 V/Nm
//Torque controller Ki - region [0] = 2000 V/(Nm*s)
//Torque controller Kp - region [1] = 150 V/Nm
//Torque controller Ki - region [1] = 12000 V/(Nm*s)
//Torque controller Kp - region [2] = 150 V/Nm
//Torque controller Ki - region [2] = 12000 V/(Nm*s)
//Flux controller Kp - region [0] = 150 V/Wb
//Flux controller Ki - region [0] = 15000 V/(Wb*s)
//Flux controller Kp - region [1] = 8000 V/Wb
//Flux controller Ki - region [1] = 900000 V/(Wb*s)
//Flux controller Kp - region [2] = 8000 V/Wb
//Flux controller Ki - region [2] = 900000 V/(Wb*s)
//Time  to switch gains - region[0] = 2 s
//Time  to switch gains - region[1] = 3 s
//Time  to switch gains - region[2] = 3 s

//Pwm Parameters
//Speed threshold to disable compensation (applied 5% hysteresis) = 6000 rpm

//Running algorithm
//Minimum speed (guard condition) to enter stopping = 228 rpm
//Minimum speed to switch off all IGBTs = 684 rpm
//Debouncer of running finished check = 5 NA
//Time to set all devices off below minimum speed = 1.8 s
//Time threshold for locked rotor at startup or in running = 4 s
//Starting debounce time to run with torque at its maximum = 3 s
//Running debounce time to run with torque at its maximum = 10 s
//Max Current for detecting locked rotor (% of max current) = 0.95 %

//Manual injection
//d current (Flux) controller Kp = 200 V/A
//d current (Flux) controller Ki = 80000 V/A/s
//q current (Torque) controller Kp = 200 V/A
//q current (Torque) controller Ki = 80000 V/A/s

//Resistance estimation algorithm
//Estimation timeout = 4 s
//Current level - 1st plateau = 4 A
//Current level - 2nd plateau = 5 A
//Current level - 3rd plateau = 1 A
//Time of 1st plateau = 0.6 s
//Time of 2nd plateau = 0.6 s
//Time of 3rd plateau = 0.4 s
//Voltage step for 1st plateau = 0.078125 V
//Voltage step for 2nd plateau = 0.078125 V
//Voltage step for 3nd plateau = 0.078125 V
//Oscillation check timer = 0.1 s
//Minimum number of samples to average = 300 NA
//Oscillation speed threshold = 30 rpm
//Time to reset resistance (declare resistance as outdated) = 6 min
//Resistance estimation call rate (sampling time) = 0.001 s
//Resistance estimation handler rate (sampling time) = 0.000125 s
//Spin speed to trigger resistance on next start up = 1710 rpm
//Time between measurement after reset = 1 min
//Number of estimation after reset = 3 NA
//Time between measurement under normal operation = 5 min
//Number of estimation in a row after spin = 3 NA
//Phase resistance calibrated at temperature = #REF! Ohm
//Temperature coefficient = 232.1 °C/Ohm
//Base temperature = 25 °C
//Samples Number = 1024 NA

//MCI PARAMETERS
//MAX_SPEED_RPM  = 19800 rpm
//MIN_SPEED_RPM  = 100 rpm
//MAX_RPM_PER_SEC_ACCEL  = 4000 rpm/s
//MAX_RPM_PER_SEC_DECEL  = 4000 rpm/s
//MIN_RPM_PER_SEC_ACCEL = 1 rpm/s
//MIN_RPM_PER_SEC_DECEL = 1 rpm/s
//STARTING_ACCEL_VALUE = 75 rpm/s
//MIN_SPEED_FOR_FIXED_ACCEL_VALUE = 0 rpm
#ifdef    MCI_INTERNAL_PARAMS

unsigned long int Mcl_Complete_Params_sBPM_SF[311] =
{
/* Max_Available_Voltage_Factor = 0.999980032444 */ 1065352881L,\
/* Observer_Stator_Resistance = 2.86999988556 */ 1077390868L,\
/* Observer_Stator_Resistance_Corr_Limits = 0.15000000596 */ 1041865114L,\
/* Observer_Stator_Resistance_Gain = 0.160000011325 */ 1042536203L,\
/* Observer_Curr_Resistance_Threshold = 4.5 */ 1083179008L,\
/* Observer_Curr_Resistance_Spd_Threshold = 4.18878698349 */ 1082526347L,\
/* Observer_Phase_Advance_Coeff = 0.0 */ 0L,\
/* Observer_Rotor_Flux_Nominal = 0.0844999998808 */ 1034751574L,\
/* Observer_G_gain = 60.0 */ 1114636288L,\
/* Observer_G_integ_gain = 0.0 */ 0L,\
/* Observer_G_integ_limits = 0.5 */ 1056964608L,\
/* Observer_G_integ_Spd_Threshold = 41.8878669739 */ 1109888301L,\
/* Observer_Pole_Pairs = 4.0 */ 1082130432L,\
/* Observer_Starting_Threshold = 500 */ 500L,\
/* Observer_PLL_Kp = 118.0 */ 1122762752L,\
/* Observer_PLL_Ki = 0.213125005364 */ 1046101361L,\
/* Observer_Pll_Integ_K = 6.25000029686e-05 */ 948114031L,\
/* DQ_Controller_Vd_Max = 165.830001831 */ 1126552699L,\
/* DQ_Controller_Force_Gains_Starting_Time = 1000 */ 1000L,\
/* DQ_Controller_Phase_Advance_Coeff = 0.000125000005937 */ 956502639L,\
/* DQ_Controller_m_index = 1.14999997616 */ 1066611507L,\
/* DQ_Controller_torque_kp_0 = 10.0 */ 1092616192L,\
/* DQ_Controller_torque_ki_0 = 0.25 */ 1048576000L,\
/* DQ_Controller_flux_kp_0 = 1500.0 */ 1153138688L,\
/* DQ_Controller_flux_ki_0 = 18.7500011921 */ 1100349440L,\
/* DQ_Controller_abs_speed_0 = 1905.0 */ 1156456448L,\
/* DQ_Controller_transition_time_0 = 80 */ 80L,\
/* DQ_Controller_torque_kp_1 = 150.0 */ 1125515264L,\
/* DQ_Controller_torque_ki_1 = 1.50000011921 */ 1069547521L,\
/* DQ_Controller_flux_kp_1 = 8000.0 */ 1174011904L,\
/* DQ_Controller_flux_ki_1 = 112.500007629 */ 1122041857L,\
/* DQ_Controller_abs_speed_1 = 14000.0 */ 1180352512L,\
/* DQ_Controller_transition_time_1 = 120 */ 120L,\
/* DQ_Controller_torque_kp_2 = 150.0 */ 1125515264L,\
/* DQ_Controller_torque_ki_2 = 1.50000011921 */ 1069547521L,\
/* DQ_Controller_flux_kp_2 = 8000.0 */ 1174011904L,\
/* DQ_Controller_flux_ki_2 = 112.500007629 */ 1122041857L,\
/* DQ_Controller_abs_speed_2 = 20000.0 */ 1184645120L,\
/* DQ_Controller_transition_time_2 = 120 */ 120L,\
/* DQ_Ref_Rotor_Flux_Nominal = 0.0844999998808 */ 1034751574L,\
/* DQ_Ref_Max_Flux = 0.20000000298 */ 1045220557L,\
/* DQ_Ref_Starting_Threshold = 1000 */ 1000L,\
/* DQ_Ref_Over_Flux_Decrement = 9.99999974738e-05 */ 953267991L,\
/* DQ_Ref_Over_Flux_Speed_Threshold = 20.9439334869 */ 1101499693L,\
/* DQ_Ref_Over_Flux_Ratio_Max = 1.20000004768 */ 1067030938L,\
/* DQ_Ref_Torque_Err_K = 0.579999983311 */ 1058306785L,\
/* DQ_Ref_Torque_Err_Sat = 0.5 */ 1056964608L,\
/* DQ_Ref_m_index = 0.980000019073 */ 1065017672L,\
/* DQ_Ref_K_torque_inv = 1.97238659859 */ 1073510186L,\
/* Running_Min_Speed_Before_All_Devices_Off = 71.6282577515 */ 1116684715L,\
/* Running_Min_Speed_Before_Stopping = 23.8760852814 */ 1103036985L,\
/* Running_Debounce_Off_Running_Finished = 5 */ 5L,\
/* Running_Time_All_Dev_Below_Min_Speed = 72 */ 72L,\
/* Running_Locked_Rotor_Starting_Or_Running = 4000 */ 4000L,\
/* Running_Locked_Rotor_Starting_Threshold = 600 */ 600L,\
/* Running_Locked_Rotor_Running_Threshold = 600 */ 600L,\
/* Running_Locked_Rotor_Current_Threshold = 48.7349967957 */ 1111683235L,\
/* Resistance_timeout_threshold = 4000 */ 4000L,\
/* Resistance_current_level_1st = 4.0 */ 1082130432L,\
/* Resistance_current_level_2nd = 5.0 */ 1084227584L,\
/* Resistance_current_level_3rd = 1.0 */ 1065353216L,\
/* Resistance_time_1st_step = 600 */ 600L,\
/* Resistance_time_2nd_step = 600 */ 600L,\
/* Resistance_time_3rd_step = 400 */ 400L,\
/* Resistance_delta_voltage_to_1st_step = 0.0399999991059 */ 1025758986L,\
/* Resistance_delta_voltage_to_2nd_step = 0.0399999991059 */ 1025758986L,\
/* Resistance_delta_voltage_to_3rd_step = 0.0781299993396 */ 1033896607L,\
/* Resistance_oscillation_check_timer = 100 */ 100L,\
/* Resistance_min_number_of_samples = 300.0 */ 1133903872L,\
/* Resistance_nominal_resistance = 2.86999988556 */ 1077390868L,\
/* Resistance_oscillation_speed_threshold = 3.14159011841 */ 1078530000L,\
/* Resistance_timer_to_reset_resistance = 14400 */ 14400L,\
/* Resistance_timer_prescaler = 7 */ 7L,\
/* Resistance_speed_threshold_to_estimate_resistance = 1710.0 */ 1154859008L,\
/* Resistance_time_estimate_resistance_after_reset = 2400 */ 2400L,\
/* Resistance_number_estimation_after_reset = 3 */ 3L,\
/* Resistance_time_estimate_resistance_normal = 12000 */ 12000L,\
/* Resistance_number_estimation_after_spin = 3 */ 3L,\
/* Resistance_Rs0 = 2.86999988556 */ 1077390868L,\
/* Resistance_Temp_Coeff = 232.100006104 */ 1130895770L,\
/* Resistance_Rs0_inv = 0.348432064056 */ 1051878832L,\
/* Resistance_Temp_Coeff_inv = 0.00430848775432 */ 999108151L,\
/* Resistance_T0 = 25.0 */ 1103626240L,\
/* Resistance_Samples_Number = 1024 */ 1024L,\
/* SpeedRef_Default_Accel = 75.0 */ 1117126656L,\
/* SpeedRef_Min_Speed_Default_Accel = 15.0 */ 1097859072L,\
/* Manual_Inj_Vd_Max = 165.830001831 */ 1126552699L,\
/* Manual_Inj_Force_Gains_Starting_Time = 0 */ 0L,\
/* Manual_Inj_Phase_Advance_Coeff = 0.0 */ 0L,\
/* Manual_Inj_m_index = 1.14999997616 */ 1066611507L,\
/* Manual_Inj_torque_kp_0 = 60.0 */ 1114636288L,\
/* Manual_Inj_torque_ki_0 = 3.25000023842 */ 1078984705L,\
/* Manual_Inj_flux_kp_0 = 60.0 */ 1114636288L,\
/* Manual_Inj_flux_ki_0 = 3.25000023842 */ 1078984705L,\
/* Manual_Inj_abs_speed_0 = 0.0 */ 0L,\
/* Manual_Inj_transition_time_0 = 0 */ 0L,\
/* Manual_Inj_torque_kp_1 = 0.0 */ 0L,\
/* Manual_Inj_torque_ki_1 = 0.0 */ 0L,\
/* Manual_Inj_flux_kp_1 = 0.0 */ 0L,\
/* Manual_Inj_flux_ki_1 = 0.0 */ 0L,\
/* Manual_Inj_abs_speed_1 = 0.0 */ 0L,\
/* Manual_Inj_transition_time_1 = 0 */ 0L,\
/* Manual_Inj_torque_kp_2 = 0.0 */ 0L,\
/* Manual_Inj_torque_ki_2 = 0.0 */ 0L,\
/* Manual_Inj_flux_kp_2 = 0.0 */ 0L,\
/* Manual_Inj_flux_ki_2 = 0.0 */ 0L,\
/* Manual_Inj_abs_speed_2 = 0.0 */ 0L,\
/* Manual_Inj_transition_time_2 = 0 */ 0L,\
/* Pwm_Speed_Threshold_InvComp = 6000.0 */ 1169915904L,\
/* sizeof_Ld_Lq_Lut = 8 */ 8L,\
/* step_inv_L_Lut = 1.0 */ 1065353216L,\
/* Ld_input_0 = 0.0 */ 0L,\
/* Ld_output_0 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_1 = 1.0 */ 1065353216L,\
/* Ld_output_1 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_2 = 2.0 */ 1073741824L,\
/* Ld_output_2 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_3 = 3.0 */ 1077936128L,\
/* Ld_output_3 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_4 = 4.0 */ 1082130432L,\
/* Ld_output_4 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_5 = 5.0 */ 1084227584L,\
/* Ld_output_5 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_6 = 6.0 */ 1086324736L,\
/* Ld_output_6 = 0.0211699996144 */ 1017998517L,\
/* Ld_input_7 = 7.0 */ 1088421888L,\
/* Ld_output_7 = 0.0211699996144 */ 1017998517L,\
/* Lq_input_0 = 0.0 */ 0L,\
/* Lq_output_0 = 0.0274400003254 */ 1021364698L,\
/* Lq_input_1 = 1.0 */ 1065353216L,\
/* Lq_output_1 = 0.0277699995786 */ 1021541865L,\
/* Lq_input_2 = 2.0 */ 1073741824L,\
/* Lq_output_2 = 0.0274199992418 */ 1021353960L,\
/* Lq_input_3 = 3.0 */ 1077936128L,\
/* Lq_output_3 = 0.0264599993825 */ 1020838564L,\
/* Lq_input_4 = 4.0 */ 1082130432L,\
/* Lq_output_4 = 0.0242599993944 */ 1019657448L,\
/* Lq_input_5 = 5.0 */ 1084227584L,\
/* Lq_output_5 = 0.0232900008559 */ 1019136684L,\
/* Lq_input_6 = 6.0 */ 1086324736L,\
/* Lq_output_6 = 0.0224099997431 */ 1018664237L,\
/* Lq_input_7 = 7.0 */ 1088421888L,\
/* Lq_output_7 = 0.0224099997431 */ 1018664237L,\
/* Ldq_input_0 = 0.0 */ 0L,\
/* Ldq_output_0 = 0.0 */ 0L,\
/* Ldq_input_1 = 1.0 */ 1065353216L,\
/* Ldq_output_1 = 0.0 */ 0L,\
/* Ldq_input_2 = 2.0 */ 1073741824L,\
/* Ldq_output_2 = 0.0 */ 0L,\
/* Ldq_input_3 = 3.0 */ 1077936128L,\
/* Ldq_output_3 = 0.0 */ 0L,\
/* Ldq_input_4 = 4.0 */ 1082130432L,\
/* Ldq_output_4 = 0.0 */ 0L,\
/* Ldq_input_5 = 5.0 */ 1084227584L,\
/* Ldq_output_5 = 0.0 */ 0L,\
/* Ldq_input_6 = 6.0 */ 1086324736L,\
/* Ldq_output_6 = 0.0 */ 0L,\
/* Ldq_input_7 = 7.0 */ 1088421888L,\
/* Ldq_output_7 = 0.0 */ 0L,\
/* Max_Squared_Inv_Current = 36.0 */ 1108344832L,\
/* Max_Design_Motor_Torque = 3.29999995232 */ 1079194419L,\
/* Rotor_Flux_Nominal = 0.0844999998808 */ 1034751574L,\
/* Force_Default_Gains_Time = 1000 */ 1000L,\
/* Max_Cos = -0.259999990463 */ 3196395192L,\
/* Kp_load_angle = 0.0 */ 0L,\
/* Ki_load_angle = 1.0 */ 1065353216L,\
/* kp_speed_0 = 0.0525211766362 */ 1029120114L,\
/* ki_speed_0 = 1.90986102098e-05 */ 933246452L,\
/* speed_abs_speed_0 = 710.040039062 */ 1144095376L,\
/* transition_time_speed_0 = 20 */ 20L,\
/* kp_speed_1 = 0.039152149111 */ 1025531393L,\
/* ki_speed_1 = 1.4920788999e-05 */ 930763853L,\
/* speed_abs_speed_1 = 1035.96008301 */ 1149337273L,\
/* transition_time_speed_1 = 20 */ 20L,\
/* kp_speed_2 = 0.0271200239658 */ 1021192912L,\
/* ki_speed_2 = 1.07429686977e-05 */ 926170291L,\
/* speed_abs_speed_2 = 4085.64013672 */ 1165974078L,\
/* transition_time_speed_2 = 20 */ 20L,\
/* kp_speed_3 = 0.0124140959233 */ 1011573886L,\
/* ki_speed_3 = 4.65528637505e-06 */ 916206747L,\
/* speed_abs_speed_3 = 20952.0 */ 1185132544L,\
/* transition_time_speed_3 = 20 */ 20L,\
/* Max_Braking_Current = 2.5 */ 1075838976L,\
/* Max_Braking_Torque = 1.0 */ 1065353216L,\
/* pole_pairs_factor = 6.0 */ 1086324736L,\
/* sizeof_MTPA_Lut = 16 */ 16L,\
/* step_inv_MTPA_Lut = 3.57142853737 */ 1080332873L,\
/* MTPA_Torque_0 = 0.0 */ 0L,\
/* MTPA_Flux_0 = 0.0854000002146 */ 1034872370L,\
/* MTPA_Torque_1 = 0.280000001192 */ 1049582633L,\
/* MTPA_Flux_1 = 0.0855000019073 */ 1034885792L,\
/* MTPA_Torque_2 = 0.560000002384 */ 1057971241L,\
/* MTPA_Flux_2 = 0.0883999988437 */ 1035275023L,\
/* MTPA_Torque_3 = 0.839999973774 */ 1062668861L,\
/* MTPA_Flux_3 = 0.0929000005126 */ 1035879003L,\
/* MTPA_Torque_4 = 1.12000000477 */ 1066359849L,\
/* MTPA_Flux_4 = 0.0988999977708 */ 1036684309L,\
/* MTPA_Torque_5 = 1.39999997616 */ 1068708659L,\
/* MTPA_Flux_5 = 0.106100000441 */ 1037650677L,\
/* MTPA_Torque_6 = 1.67999994755 */ 1071057469L,\
/* MTPA_Flux_6 = 0.109800003469 */ 1038147283L,\
/* MTPA_Torque_7 = 1.96000003815 */ 1073406280L,\
/* MTPA_Flux_7 = 0.111400000751 */ 1038362031L,\
/* MTPA_Torque_8 = 2.24000000954 */ 1074748457L,\
/* MTPA_Flux_8 = 0.112700000405 */ 1038536514L,\
/* MTPA_Torque_9 = 2.51999998093 */ 1075922862L,\
/* MTPA_Flux_9 = 0.121299996972 */ 1039690786L,\
/* MTPA_Torque_10 = 2.79999995232 */ 1077097267L,\
/* MTPA_Flux_10 = 0.130099996924 */ 1040529647L,\
/* MTPA_Torque_11 = 3.07999992371 */ 1078271672L,\
/* MTPA_Flux_11 = 0.139400005341 */ 1041153760L,\
/* MTPA_Torque_12 = 3.3599998951 */ 1079446077L,\
/* MTPA_Flux_12 = 0.148900002241 */ 1041791294L,\
/* MTPA_Torque_13 = 3.6400001049 */ 1080620483L,\
/* MTPA_Flux_13 = 0.158500000834 */ 1042435539L,\
/* MTPA_Torque_14 = 3.92000007629 */ 1081794888L,\
/* MTPA_Flux_14 = 0.168099999428 */ 1043079784L,\
/* MTPA_Torque_15 = 4.19999980927 */ 1082549862L,\
/* MTPA_Flux_15 = 0.168099999428 */ 1043079784L,\
/* sizeof_MTPV_Lut = 16 */ 16L,\
/* step_inv_MTPV_Lut = 90.9090957642 */ 1119211893L,\
/* MTPV_Flux_0 = 0.00700000021607 */ 1004888130L,\
/* MTPV_Torque_0 = 0.064099997282 */ 1032013532L,\
/* MTPV_Flux_1 = 0.0179999992251 */ 1016296636L,\
/* MTPV_Torque_1 = 0.391999989748 */ 1053340729L,\
/* MTPV_Flux_2 = 0.0289999991655 */ 1022202216L,\
/* MTPV_Torque_2 = 0.655499994755 */ 1059573465L,\
/* MTPV_Flux_3 = 0.0399999991059 */ 1025758986L,\
/* MTPV_Torque_3 = 0.904200017452 */ 1063745959L,\
/* MTPV_Flux_4 = 0.0509999990463 */ 1028711776L,\
/* MTPV_Torque_4 = 1.1385999918 */ 1066515877L,\
/* MTPV_Flux_5 = 0.0619999989867 */ 1031664566L,\
/* MTPV_Torque_5 = 1.35580003262 */ 1068337883L,\
/* MTPV_Flux_6 = 0.0729999989271 */ 1033208070L,\
/* MTPV_Torque_6 = 1.55190002918 */ 1069982889L,\
/* MTPV_Flux_7 = 0.0839999988675 */ 1034684465L,\
/* MTPV_Torque_7 = 1.69990003109 */ 1071224403L,\
/* MTPV_Flux_8 = 0.0949999988079 */ 1036160860L,\
/* MTPV_Torque_8 = 2.08010005951 */ 1074077788L,\
/* MTPV_Flux_9 = 0.105999998748 */ 1037637255L,\
/* MTPV_Torque_9 = 2.5978000164 */ 1076249179L,\
/* MTPV_Flux_10 = 0.116999998689 */ 1039113650L,\
/* MTPV_Torque_10 = 3.1944000721 */ 1078751501L,\
/* MTPV_Flux_11 = 0.12800000608 */ 1040388719L,\
/* MTPV_Torque_11 = 3.29999995232 */ 1079194419L,\
/* MTPV_Flux_12 = 0.138999998569 */ 1041126916L,\
/* MTPV_Torque_12 = 3.29999995232 */ 1079194419L,\
/* MTPV_Flux_13 = 0.15000000596 */ 1041865114L,\
/* MTPV_Torque_13 = 3.29999995232 */ 1079194419L,\
/* MTPV_Flux_14 = 0.16099999845 */ 1042603311L,\
/* MTPV_Torque_14 = 3.29999995232 */ 1079194419L,\
/* MTPV_Flux_15 = 0.172000005841 */ 1043341509L,\
/* MTPV_Torque_15 = 3.29999995232 */ 1079194419L,\
/* sizeof_Rotor_Flux_Lut = 8 */ 8L,\
/* step_inv_Rotor_Flux_Lut = 1.0 */ 1065353216L,\
/* RotorFlux_input_0 = 1.0 */ 1065353216L,\
/* RotorFlux_output_0 = 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_1 = 2.0 */ 1073741824L,\
/* RotorFlux_output_1 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_2 = 3.0 */ 1077936128L,\
/* RotorFlux_output_2 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_3 = 4.0 */ 1082130432L,\
/* RotorFlux_output_3 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_4 = 5.0 */ 1084227584L,\
/* RotorFlux_output_4 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_5 = 6.0 */ 1086324736L,\
/* RotorFlux_output_5 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_6 = 7.0 */ 1088421888L,\
/* RotorFlux_output_6 0.0844999998808 */ 1034751574L,\
/* RotorFlux_input_7 = 8.0 */ 1090519040L,\
/* RotorFlux_output_7 0.0844999998808 */ 1034751574L,\
/*Current_Offset_Comp_Speed_Hyst_Thr = =Current Offset Comp Speed Thr hysteresis/100*/                     0L,\
/*Current_Offset_Comp_Current_Thr = =Current Offset Comp Current Thr*/                     0L,\
/*Current_Offset_Comp_Max_Current_Comp = =Current Offset Comp Max Current Compensation*/                     0L,\
/*Current_Offset_Comp_Full_Cycle_Cnt = =Current Offset Comp Full Cycle Counter*/                     0L,\
/*Input Processing Dummy 1 = */                     0L,\
/*Input Processing Dummy 2 = */                     0L,\
/*Phase_Advance_Coeff = =Phase Advance Coefficient*/                     0L,\
/*Resistance_Adapt_Recovery = =Stator Resistance adaptation recovery*/                     950976884L,\
/*Swap Phase Time Threshold  = =Swap Phase Time Threshold /Observer call rate */                     0L,\
/*Swap Phase Current Threshold  = =Swap Phase Current Threshold*/                     1083179008L,\
/*Swap Phase Speed  Threshold  = =Swap Phase Speed Threshold/60*2*pi()*/                     1082526354L,\
/*Pll_Engage_Speed_Thr = =PLL_Engage Speed Threshold /60*'PolePairs*2*pi()*/                     1099303570L,\
/*Pll_Engage_Speed_Err_Thr = =PLL_Engage Speed Error Threshold /60*'PolePairs*2*pi()*/                     1099303570L,\
/*Observer Dummy 1 = */                     0L,\
/*Observer Dummy 2 = */                     0L,\
/*Min_Braking_Diss_Torque_Low_Thr = =Min Braking Diss Torque Low Thr*/                     1034147594L,\
/*Min_Braking_Diss_Torque_High_Thr = =Min Braking Diss Torque High Thr*/                     1036831949L,\
/*Max_Braking_Gen_Low_Speed = =Max Braking Gen Low Speed*/                     1045220557L,\
/*Max_Braking_Gen_High_Speed = =Max Braking Gen High Speed*/                     0L,\
/*Max_Braking_Gen_Low_High_Speed_Thr = =Max Braking Gen Low/High Speed Threshold/60*2*pi()*/                     1128724400L,\
/*Braking_Resistance_Percentage = =Braking Resistance Percentage/100*/                     1064514355L,\
/*Braking_Mode = =Braking Mode */                     0L,\
/*Speed Regulator Dummy 1 = */                     0L,\
/*Speed Regulator Dummy 2 = */                     0L,\
/*Braking Mode = =Braking Mode */                     0L,\
/*Id_Braking_Prop_Gain = =Id Braking Prop Gain */                     1017370378L,\
/*Id_Braking_Step_Back = =Id Braking Step Back*/                     1028443341L,\
/*Overflux_Charging = =Overflux Charging*/                     981668463L,\
/*Overflux_Min_Perc = =Overflux min percentage*/                     0L,\
/*Flux_Adaptation_G_Gain = =Flux Adaptation G Gain *Observer call rate*/                     936490775L,\
/*Flux_Adaptation_Low_Limit = =(1-FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1030899525L,\
/*Flux_Adaptation_High_Limit = =(1+FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1038153993L,\
/*Dq Ref Dummy 1 = */                     0L,\
/*Dq Ref Dummy 2 = */                     0L,\
/*MAX_SPEED_RPM  = =MAX_SPEED_RPM */                     19800L,\
/*MIN_SPEED_RPM  = =MIN_SPEED_RPM */                     100L,\
/*MAX_RPM_PER_SEC_ACCEL  = =MAX_RPM_PER_SEC_ACCEL */                     4000L,\
/*MAX_RPM_PER_SEC_DECEL  = =MAX_RPM_PER_SEC_DECEL */                     4000L,\
/*MIN_RPM_PER_SEC_ACCEL = =MIN_RPM_PER_SEC_ACCEL*/                     1L,\
/*MIN_RPM_PER_SEC_DECEL = =MIN_RPM_PER_SEC_DECEL*/                     1L,\
};

#endif
#endif //MCL_COMPLETE_SBPM_PRM_H
