/**
 *  @file        Mcl_Additional_DD_prm.h
 *  @brief       DTC Loop Parameters for 3-phase motors.
 *
 *               ==== AUTOMATIC GENERATED FILE! DO NOT TOUCH IT, USE EXCEL MACRO! ====
 *
 *  @details     This module defines all parameters of the DTC control loop for 3-phase motors. Created in 10/3/2022 9:57 
 *               Setting File Parameters for DD TM9
 *               Generated from https://docs.google.com/spreadsheets/d/1w8wi93MUvhygK8mfTXd0jktLxF5UVJp0Knq2R5aEFWw/edit
 *               Generated by luigi_fagnano@whirlpool.com
 *  @copyright   Copyright 2022.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL
 *
 */

#ifndef MCL_ADDITIONAL_DD_PRM_H
#define MCL_ADDITIONAL_DD_PRM_H


//=====================================================================================================================
//-------------------------------------- PUBLIC (Extern Variables, Constants & Defines) -------------------------------
//=====================================================================================================================


#include "MciParametersLoader_prv.h"


//DTC Phisical Motor Control Parameters

//0.1
//Stator Resistance = 5.6 Ohm
//Rotor flux  = 0.173 Wb
//Maximum electromagnetic torque = 26 Nm

//Pole pairs
//Current Offset Comp Speed Thr (0 to disable) = 800 rpm
//Current Offset Comp Speed Thr hysteresis = 5 %
//Current Offset Comp Current Thr = 1.414 A
//Current Offset Comp Max Current Compensation = 0.05 A
//Current Offset Comp Full Cycle Counter = 15 na

//Hardware (inverter) configuration
//Maximum peak phase current = 6.4 A

//Observer Parameters
//Stator Resistance adaptation limits = 7 %
//Stator Resistance adaptation gain = 160 Ohm/(Wb*s)
//Stator Resistance adaptation recovery = 83.33 Ohm*us
//Current threshold to enable resistance adaptation = 4.5 A
//Speed threshold to enable resistance adaptation = 4 rpm
//Observer G gain = 60 V/Wb
//Observer Integ G gain = 0 V/Wb/s
//Observer Integ Limits = 0.5 V
//Observer Integ activation speed threshold = 400 rpm
//Stator Resistance adaptation offset = 0 Ohm
//Phase Advance Coefficient (0 to disable) = 0 NA
//Starting time threshold = 0.5 s
//PLL - Kp gain = 70 1/s
//PLL - Ki gain = 800 Stat
//PLL - Engage Speed Threshold  = 4 rpm
//PLL - Engage Speed Error Threshold  = 9 rpm
//Observer call rate (sampling time) = 0.000125 s
//Swap Phase Time Threshold (0 to disable) = 1 s
//Swap Phase Current Threshold = 4.5 A
//Swap Phase Speed Threshold = 4 rpm

//Speed Controller Parameters
//Maximum cosine of load angle = -0.26 NA
//Load angle controller Kp = 30 Nm
//Load angle controller Ki = 2000 Nm/s
//Time to force the use of default gains = 1 s
//Default Acceleration = 8 rpm/s
//Min Speed Default Acceleration = 2 rpm
//Max Braking Diss Torque = 10 Nm
//Max Braking  Diss Current = 2.2 A
//Min Braking Diss Torque Low Thr = 0.9359999999999999 Nm
//Min Braking Diss Torque High Thr = 1.17 Nm
//Max Braking Gen Low Speed = 2.34 Nm
//Max Braking Gen High Speed = 0 Nm
//Max Braking Gen Low/High Speed Threshold = 160 rpm
//Braking Resistance Percentage = 95 %
//Id Braking Prop Gain  = 0.02 NA
//Id Braking Step Back = 0.05 A/ms
//Braking Mode (0 = conservative) = 1 NA

//DQ Reference Generator Parameters
//Starting time = 1 s
//Maximum designed flux  = 0.5 Wb
//Speed threshold to enable/disable overflux = 15 rpm
//Percentage to be applied of overflux = 40 %
//Overflux decrement = 0.0007 Wb
//Overflux Charging = 0.1 %
//Overflux min percentage = 0 %
//Flux Adaptation G Gain (0 to disable) = 0.2 Wb/(A*Ts)
//FLux Adaptation Hysteresis Percentage = 30 %
//K (torque error compensation) = 0 1/Nm
//Torque error compensation saturation = 0.5 NA
//Max Modulation Index(REF) = 100 %

//DQ Controllers Parameters
//Starting time to force gains = 1 s
//Phase advance coefficient = 1 NA
//Max Modulation Index (CTRL) = 115 %
//Pi Volt Margin for Vd_Max = 140 V
//Absolute speed threshold range - region[0] = 200 rpm
//Absolute speed threshold range - region[1] = 800 rpm
//Absolute speed threshold range - region[2] = 1500 rpm
//Torque controller Kp - region [0] = 2.5 V/Nm
//Torque controller Ki - region [0] = 250 V/(Nm*s)
//Torque controller Kp - region [1] = 16.2 V/Nm
//Torque controller Ki - region [1] = 1216 V/(Nm*s)
//Torque controller Kp - region [2] = 14.9 V/Nm
//Torque controller Ki - region [2] = 1322 V/(Nm*s)
//Flux controller Kp - region [0] = 300 V/Wb
//Flux controller Ki - region [0] = 60745 V/(Wb*s)
//Flux controller Kp - region [1] = 4902 V/Wb
//Flux controller Ki - region [1] = 1450000 V/(Wb*s)
//Flux controller Kp - region [2] = 4902 V/Wb
//Flux controller Ki - region [2] = 1450000 V/(Wb*s)
//Time  to switch gains - region[0] = 2 s
//Time  to switch gains - region[1] = 3 s
//Time  to switch gains - region[2] = 3 s

//Pwm Parameters
//Speed threshold to disable compensation (applied 5% hysteresis) = 200 rpm

//Running algorithm
//Minimum speed (guard condition) to enter stopping = 20 rpm
//Minimum speed to switch off all IGBTs = 5 rpm
//Debouncer of running finished check = 0 NA
//Time to set all devices off below minimum speed = 1.8 s
//Time threshold for locked rotor at startup or in running = 4 s
//Starting debounce time to run with torque at its maximum = 3 s
//Running debounce time to run with torque at its maximum = 3 s
//Max Current for detecting locked rotor (% of max current) = 0.92 %

//Manual injection
//d current (Flux) controller Kp = 60 V/A
//d current (Flux) controller Ki = 26000 V/A/s
//q current (Torque) controller Kp = 60 V/A
//q current (Torque) controller Ki = 26000 V/A/s

//Resistance estimation algorithm
//Estimation timeout = 4 s
//Current level - 1st plateau = 4 A
//Current level - 2nd plateau = 5 A
//Current level - 3rd plateau = 1 A
//Time of 1st plateau = 0.6 s
//Time of 2nd plateau = 0.6 s
//Time of 3rd plateau = 0.4 s
//Voltage step for 1st plateau = 0.04 V
//Voltage step for 2nd plateau = 0.04 V
//Voltage step for 3nd plateau = 0.078125 V
//Oscillation check timer = 0.1 s
//Minimum number of samples to average = 300 NA
//Oscillation speed threshold = 30 rpm
//Time to reset resistance (declare resistance as outdated) = 6 min
//Resistance estimation call rate (sampling time) = 0.001 s
//Resistance estimation handler rate (sampling time) = 0.000125 s
//Spin speed to trigger resistance on next start up = 171 rpm
//Time between measurement after reset = 1 min
//Number of estimation after reset = 3 NA
//Time between measurement under normal operation = 5 min
//Number of estimation in a row after spin = 3 NA
//Phase resistance calibrated at temperature = 5.6 Ohm
//Temperature coefficient = 232.1 °C/Ohm
//Base temperature = 25 °C
//Samples Number = 1024 NA

//MCI PARAMETERS
//MAX_SPEED_RPM  = 2000 rpm
//MIN_SPEED_RPM  = 10 rpm
//MAX_RPM_PER_SEC_ACCEL  = 85 rpm/s
//MAX_RPM_PER_SEC_DECEL  = 50 rpm/s
//MIN_RPM_PER_SEC_ACCEL = 1 rpm/s
//MIN_RPM_PER_SEC_DECEL = 1 rpm/s




signed long int Mcl_Additional_Params_DD_SF[40] =
{
/*Current_Offset_Comp_Speed_Hyst_Thr = =Current Offset Comp Speed Thr hysteresis/100*/                     1028443341L,\
/*Current_Offset_Comp_Current_Thr = =Current Offset Comp Current Thr*/                     1068826100L,\
/*Current_Offset_Comp_Max_Current_Comp = =Current Offset Comp Max Current Compensation*/                     1028443341L,\
/*Current_Offset_Comp_Full_Cycle_Cnt = =Current Offset Comp Full Cycle Counter*/                     15L,\
/*Input Processing Dummy 1 = */                     0L,\
/*Input Processing Dummy 2 = */                     0L,\
/*Phase_Advance_Coeff = =Phase Advance Coefficient*/                     0L,\
/*Resistance_Adapt_Recovery = =Stator Resistance adaptation recovery*/                     950976884L,\
/*Swap Phase Time Threshold  = =Swap Phase Time Threshold /Observer call rate */                     8000L,\
/*Swap Phase Current Threshold  = =Swap Phase Current Threshold*/                     1083179008L,\
/*Swap Phase Speed  Threshold  = =Swap Phase Speed Threshold/60*2*pi()*/                     1054242640L,\
/*Pll_Engage_Speed_Thr = =PLL_Engage Speed Threshold /60*'PolePairs*2*pi()*/                     1089553978L,\
/*Pll_Engage_Speed_Err_Thr = =PLL_Engage Speed Error Threshold /60*'PolePairs*2*pi()*/                     1099413376L,\
/*Observer Dummy 1 = */                     0L,\
/*Observer Dummy 2 = */                     0L,\
/*Min_Braking_Diss_Torque_Low_Thr = =Min Braking Diss Torque Low Thr*/                     1064279474L,\
/*Min_Braking_Diss_Torque_High_Thr = =Min Braking Diss Torque High Thr*/                     1066779279L,\
/*Max_Braking_Gen_Low_Speed = =Max Braking Gen Low Speed*/                     1075167887L,\
/*Max_Braking_Gen_High_Speed = =Max Braking Gen High Speed*/                     0L,\
/*Max_Braking_Gen_Low_High_Speed_Thr = =Max Braking Gen Low/High Speed Threshold/60*2*pi()*/                     1099303570L,\
/*Braking_Resistance_Percentage = =Braking Resistance Percentage/100*/                     1064514355L,\
/*Braking_Mode = =Braking Mode */                     1L,\
/*Speed Regulator Dummy 1 = */                     0L,\
/*Speed Regulator Dummy 2 = */                     0L,\
/*Braking Mode = =Braking Mode */                     1L,\
/*Id_Braking_Prop_Gain = =Id Braking Prop Gain */                     1017370378L,\
/*Id_Braking_Step_Back = =Id Braking Step Back*/                     1028443341L,\
/*Overflux_Charging = =Overflux Charging*/                     981668463L,\
/*Overflux_Min_Perc = =Overflux min percentage*/                     0L,\
/*Flux_Adaptation_G_Gain = =Flux Adaptation G Gain *Observer call rate*/                     936490775L,\
/*Flux_Adaptation_Low_Limit = =(1-FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1039663943L,\
/*Flux_Adaptation_High_Limit = =(1+FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1046891568L,\
/*Dq Ref Dummy 1 = */                     0L,\
/*Dq Ref Dummy 2 = */                     0L,\
/*MAX_SPEED_RPM  = =MAX_SPEED_RPM */                     2000L,\
/*MIN_SPEED_RPM  = =MIN_SPEED_RPM */                     10L,\
/*MAX_RPM_PER_SEC_ACCEL  = =MAX_RPM_PER_SEC_ACCEL */                     85L,\
/*MAX_RPM_PER_SEC_DECEL  = =MAX_RPM_PER_SEC_DECEL */                     50L,\
/*MIN_RPM_PER_SEC_ACCEL = =MIN_RPM_PER_SEC_ACCEL*/                     1L,\
/*MIN_RPM_PER_SEC_DECEL = =MIN_RPM_PER_SEC_DECEL*/                     1L,\
};


#endif //MCL_ADDITIONAL_DD_PRM_H
