/**
 *  @file        Mcl_Additional_DD_prm.h
 *  @brief       DTC Loop Parameters for 3-phase motors.
 *
 *               ==== AUTOMATIC GENERATED FILE! DO NOT TOUCH IT, USE EXCEL MACRO! ====
 *
 *  @details     This module defines all parameters of the DTC control loop for 3-phase motors. Created in 31/8/2021 15:12 
 *               Setting File Parameters for DD Hefei TM9
 *               Generated from https://docs.google.com/spreadsheets/d/17dijlEdOyEOqoWQjgcuCBuNmN_a1QMehYWMrLnuljfc/edit
 *               Generated by luigi_fagnano@whirlpool.com
 *  @copyright   Copyright 2021.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL
 *
 */

#ifndef MCL_COMPLETE_DD_PRM_H
#define MCL_COMPLETE_DD_PRM_H


//=====================================================================================================================
//-------------------------------------- PUBLIC (Extern Variables, Constants & Defines) -------------------------------
//=====================================================================================================================


#include "MciParametersLoader_prv.h"


//DTC Phisical Motor Control Parameters

//0.1
//Stator Resistance = 5.6 Ohm
//Rotor flux  = 0.173 Wb
//Maximum electromagnetic torque = 26 Nm

//Pole pairs
//Current Offset Comp Speed Thr (0 to disable) = 800 rpm
//Current Offset Comp Speed Thr hysteresis = 5 %
//Current Offset Comp Current Thr = 1.414 A
//Current Offset Comp Max Current Compensation = 0.05 A
//Current Offset Comp Full Cycle Counter = 15 na

//Hardware (inverter) configuration
//Maximum peak phase current = 6.4 A

//Observer Parameters
//Stator Resistance adaptation limits = 7 %
//Stator Resistance adaptation gain = 160 Ohm/(Wb*s)
//Stator Resistance adaptation recovery = 83.33 Ohm*us
//Current threshold to enable resistance adaptation = 4.5 A
//Speed threshold to enable resistance adaptation = 4 rpm
//Observer G gain = 60 V/Wb
//Observer Integ G gain = 0 V/Wb/s
//Observer Integ Limits = 0.5 V
//Observer Integ activation speed threshold = 400 rpm
//Stator Resistance adaptation offset = 0 Ohm
//Phase Advance Coefficient (0 to disable) = 0 NA
//Starting time threshold = 0.5 s
//PLL - Kp gain = 70 1/s
//PLL - Ki gain = 800 Stat
//PLL - Engage Speed Threshold  = 9 rpm
//Observer call rate (sampling time) = 0.000125 s
//Swap Phase Time Activation Sample (0 to disable) = 1 s

//Speed Controller Parameters
//Maximum cosine of load angle = -0.26 NA
//Load angle controller Kp = 30 Nm
//Load angle controller Ki = 2000 Nm/s
//Time to force the use of default gains = 1 s
//Default Acceleration = 8 rpm/s
//Min Speed Default Acceleration = 2 rpm
//Max Braking Diss Torque = 10 Nm
//Max Braking  Diss Current = 2.2 A
//Min Braking Diss Torque = 1.17 Nm
//Min Braking Diss Torque Threshold = 80 %
//Max Braking Gen Low Speed = 2.34 Nm
//Max Braking Gen High Speed = 0 Nm
//Max Braking Gen Low/High Speed Threshold = 160 rpm
//Braking Resistance Percentage = 95 %
//Id Braking Prop Gain  = 0.02 A
//Id Braking Step Back = 0.05 A
//Braking Mode = 1 NA

//DQ Reference Generator Parameters
//Starting time = 1 s
//Maximum designed flux  = 0.5 Wb
//Speed threshold to enable/disable overflux = 15 rpm
//Percentage to be applied of overflux = 40 %
//Overflux decrement = 0.0007 Wb
//Overflux Charging = 0.001 Wb
//Overflux min percentage = 0 %
//Overflux activation threshold  = 100 %
//Flux Adaptation G Gain (0 to disable) = 0.2 Wb/A*Ts
//FLux Adaptation Hysteresis Percentage = 30 %
//K (torque error compensation) = 0 1/Nm
//Torque error compensation saturation = 0.5 NA
//Max Modulation Index(REF) = 100 %

//DQ Controllers Parameters
//Starting time to force gains = 1 s
//Phase advance coefficient = 1 NA
//Max Modulation Index (CTRL) = 115 %
//Pi Volt Margin for Vd_Max = 140 V
//Absolute speed threshold range - region[0] = 200 rpm
//Absolute speed threshold range - region[1] = 800 rpm
//Absolute speed threshold range - region[2] = 1500 rpm
//Torque controller Kp - region [0] = 2.5 V/Nm
//Torque controller Ki - region [0] = 250 V/(Nm*s)
//Torque controller Kp - region [1] = 16.2 V/Nm
//Torque controller Ki - region [1] = 1216 V/(Nm*s)
//Torque controller Kp - region [2] = 14.9 V/Nm
//Torque controller Ki - region [2] = 1322 V/(Nm*s)
//Flux controller Kp - region [0] = 300 V/Wb
//Flux controller Ki - region [0] = 60745 V/(Wb*s)
//Flux controller Kp - region [1] = 4902 V/Wb
//Flux controller Ki - region [1] = 1450000 V/(Wb*s)
//Flux controller Kp - region [2] = 4902 V/Wb
//Flux controller Ki - region [2] = 1450000 V/(Wb*s)
//Time  to switch gains - region[0] = 2 s
//Time  to switch gains - region[1] = 3 s
//Time  to switch gains - region[2] = 3 s

//Pwm Parameters
//Speed threshold to disable compensation (applied 5% hysteresis) = 200 rpm

//Running algorithm
//Minimum speed (guard condition) to enter stopping = 20 rpm
//Minimum speed to switch off all IGBTs = 5 rpm
//Debouncer of running finished check = 0 NA
//Time to set all devices off below minimum speed = 1.8 s
//Time threshold for locked rotor at startup or in running = 4 s
//Starting debounce time to run with torque at its maximum = 3 s
//Running debounce time to run with torque at its maximum = 3 s
//Max Current for detecting locked rotor (% of max current) = 0.92 %

//Manual injection
//d current (Flux) controller Kp = 60 V/A
//d current (Flux) controller Ki = 26000 V/A/s
//q current (Torque) controller Kp = 60 V/A
//q current (Torque) controller Ki = 26000 V/A/s

//Resistance estimation algorithm
//Estimation timeout = 4 s
//Current level - 1st plateau = 4 A
//Current level - 2nd plateau = 5 A
//Current level - 3rd plateau = 1 A
//Time of 1st plateau = 0.6 s
//Time of 2nd plateau = 0.6 s
//Time of 3rd plateau = 0.4 s
//Voltage step for 1st plateau = 0.04 V
//Voltage step for 2nd plateau = 0.04 V
//Voltage step for 3nd plateau = 0.078125 V
//Oscillation check timer = 0.1 s
//Minimum number of samples to average = 300 NA
//Oscillation speed threshold = 30 rpm
//Time to reset resistance (declare resistance as outdated) = 6 min
//Resistance estimation call rate (sampling time) = 0.001 s
//Resistance estimation handler rate (sampling time) = 0.000125 s
//Spin speed to trigger resistance on next start up = 171 rpm
//Time between measurement after reset = 1 min
//Number of estimation after reset = 3 NA
//Time between measurement under normal operation = 5 min
//Number of estimation in a row after spin = 3 NA
//Phase resistance calibrated at temperature = 5.6 Ohm
//Temperature coefficient = 232.1 °C/Ohm
//Base temperature = 25 °C
//Samples Number = 1024 NA

//MCI PARAMETERS
//MAX_SPEED_RPM  = 2000 rpm
//MIN_SPEED_RPM  = 10 rpm
//MAX_RPM_PER_SEC_ACCEL  = 85 rpm/s
//MAX_RPM_PER_SEC_DECEL  = 50 rpm/s
//MIN_RPM_PER_SEC_ACCEL = 1 rpm/s
//MIN_RPM_PER_SEC_DECEL = 1 rpm/s
//STARTING_ACCEL_VALUE = 10 rpm/s
//MIN_SPEED_FOR_FIXED_ACCEL_VALUE = 0 rpm
#ifdef    MCI_INTERNAL_PARAMS

unsigned long int Mcl_Complete_Params_DD_SF[311] =
{
/* Max_Available_Voltage_Factor = 0.9990000128746033 */ 1065336439L,\
/* Observer_Stator_Resistance = 5.599999904632568 */ 1085485875L,\
/* Observer_Stator_Resistance_Corr_Limits = 0.07000000029802322 */ 1032805417L,\
/* Observer_Stator_Resistance_Gain = 0.1600000113248825 */ 1042536203L,\
/* Observer_Curr_Resistance_Threshold = 4.5 */ 1083179008L,\
/* Observer_Curr_Resistance_Spd_Threshold = 0.4188787043094635 */ 1054242629L,\
/* Observer_Phase_Advance_Coeff = 0.0 */ 0L,\
/* Observer_Rotor_Flux_Nominal = 0.17299999296665192 */ 1043408617L,\
/* Observer_G_gain = 60.0 */ 1114636288L,\
/* Observer_G_integ_gain = 0.0 */ 0L,\
/* Observer_G_integ_limits = 0.5 */ 1056964608L,\
/* Observer_G_integ_Spd_Threshold = 41.88786697387695 */ 1109888301L,\
/* Observer_Pole_Pairs = 18.0 */ 1099956224L,\
/* Observer_Starting_Threshold = 500 */ 500L,\
/* Observer_PLL_Kp = 70.0 */ 1116471296L,\
/* Observer_PLL_Ki = 0.05000000074505806 */ 1028443341L,\
/* Observer_Pll_Integ_K = 6.25000029685907e-05 */ 948114031L,\
/* DQ_Controller_Vd_Max = 193.75999450683594 */ 1128383119L,\
/* DQ_Controller_Force_Gains_Starting_Time = 1000 */ 1000L,\
/* DQ_Controller_Phase_Advance_Coeff = 0.0001250000059371814 */ 956502639L,\
/* DQ_Controller_m_index = 1.149999976158142 */ 1066611507L,\
/* DQ_Controller_torque_kp_0 = 2.5 */ 1075838976L,\
/* DQ_Controller_torque_ki_0 = 0.03125 */ 1023410176L,\
/* DQ_Controller_flux_kp_0 = 300.0 */ 1133903872L,\
/* DQ_Controller_flux_ki_0 = 7.593125343322754 */ 1089665762L,\
/* DQ_Controller_abs_speed_0 = 200.0 */ 1128792064L,\
/* DQ_Controller_transition_time_0 = 80 */ 80L,\
/* DQ_Controller_torque_kp_1 = 16.170000076293945 */ 1098996777L,\
/* DQ_Controller_torque_ki_1 = 0.15200001001358032 */ 1041999332L,\
/* DQ_Controller_flux_kp_1 = 4902.89013671875 */ 1167669023L,\
/* DQ_Controller_flux_ki_1 = 181.25001525878906 */ 1127563265L,\
/* DQ_Controller_abs_speed_1 = 800.0 */ 1145569280L,\
/* DQ_Controller_transition_time_1 = 120 */ 120L,\
/* DQ_Controller_torque_kp_2 = 14.869999885559082 */ 1097722757L,\
/* DQ_Controller_torque_ki_2 = 0.1652500033378601 */ 1042888524L,\
/* DQ_Controller_flux_kp_2 = 4902.89990234375 */ 1167669043L,\
/* DQ_Controller_flux_ki_2 = 181.25001525878906 */ 1127563265L,\
/* DQ_Controller_abs_speed_2 = 1500.0 */ 1153138688L,\
/* DQ_Controller_transition_time_2 = 120 */ 120L,\
/* DQ_Ref_Rotor_Flux_Nominal = 0.17299999296665192 */ 1043408617L,\
/* DQ_Ref_Max_Flux = 0.5 */ 1056964608L,\
/* DQ_Ref_Starting_Threshold = 1000 */ 1000L,\
/* DQ_Ref_Over_Flux_Decrement = 0.000699999975040555 */ 976715828L,\
/* DQ_Ref_Over_Flux_Speed_Threshold = 1.5707950592041016 */ 1070141392L,\
/* DQ_Ref_Over_Flux_Ratio_Max = 1.399999976158142 */ 1068708659L,\
/* DQ_Ref_Torque_Err_K = 0.0 */ 0L,\
/* DQ_Ref_Torque_Err_Sat = 0.5 */ 1056964608L,\
/* DQ_Ref_m_index = 1.0 */ 1065353216L,\
/* DQ_Ref_K_torque_inv = 0.21408693492412567 */ 1046165915L,\
/* Running_Min_Speed_Before_All_Devices_Off = 2.094393491744995 */ 1074137739L,\
/* Running_Min_Speed_Before_Stopping = 2.094393491744995 */ 1074137739L,\
/* Running_Debounce_Off_Running_Finished = 0 */ 0L,\
/* Running_Time_All_Dev_Below_Min_Speed = 72 */ 72L,\
/* Running_Locked_Rotor_Starting_Or_Running = 4000 */ 4000L,\
/* Running_Locked_Rotor_Starting_Threshold = 600 */ 600L,\
/* Running_Locked_Rotor_Running_Threshold = 600 */ 600L,\
/* Running_Locked_Rotor_Current_Threshold = 52.00281524658203 */ 1112539874L,\
/* Resistance_timeout_threshold = 4000 */ 4000L,\
/* Resistance_current_level_1st = 4.0 */ 1082130432L,\
/* Resistance_current_level_2nd = 5.0 */ 1084227584L,\
/* Resistance_current_level_3rd = 1.0 */ 1065353216L,\
/* Resistance_time_1st_step = 600 */ 600L,\
/* Resistance_time_2nd_step = 600 */ 600L,\
/* Resistance_time_3rd_step = 400 */ 400L,\
/* Resistance_delta_voltage_to_1st_step = 0.03999999910593033 */ 1025758986L,\
/* Resistance_delta_voltage_to_2nd_step = 0.03999999910593033 */ 1025758986L,\
/* Resistance_delta_voltage_to_3rd_step = 0.07812999933958054 */ 1033896607L,\
/* Resistance_oscillation_check_timer = 100 */ 100L,\
/* Resistance_min_number_of_samples = 300.0 */ 1133903872L,\
/* Resistance_nominal_resistance = 5.599999904632568 */ 1085485875L,\
/* Resistance_oscillation_speed_threshold = 0.31415900588035583 */ 1050728819L,\
/* Resistance_timer_to_reset_resistance = 14400 */ 14400L,\
/* Resistance_timer_prescaler = 7 */ 7L,\
/* Resistance_speed_threshold_to_estimate_resistance = 171.0 */ 1126891520L,\
/* Resistance_time_estimate_resistance_after_reset = 2400 */ 2400L,\
/* Resistance_number_estimation_after_reset = 3 */ 3L,\
/* Resistance_time_estimate_resistance_normal = 12000 */ 12000L,\
/* Resistance_number_estimation_after_spin = 3 */ 3L,\
/* Resistance_Rs0 = 5.599999904632568 */ 1085485875L,\
/* Resistance_Temp_Coeff = 232.10000610351562 */ 1130895770L,\
/* Resistance_Rs0_inv = 0.1785714328289032 */ 1043782510L,\
/* Resistance_Temp_Coeff_inv = 0.004308487754315138 */ 999108151L,\
/* Resistance_T0 = 25.0 */ 1103626240L,\
/* Resistance_Samples_Number = 1024 */ 1024L,\
/* SpeedRef_Default_Accel = 8.0 */ 1090519040L,\
/* SpeedRef_Min_Speed_Default_Accel = 2.0 */ 1073741824L,\
/* Manual_Inj_Vd_Max = 193.75999450683594 */ 1128383119L,\
/* Manual_Inj_Force_Gains_Starting_Time = 0 */ 0L,\
/* Manual_Inj_Phase_Advance_Coeff = 0.0 */ 0L,\
/* Manual_Inj_m_index = 1.149999976158142 */ 1066611507L,\
/* Manual_Inj_torque_kp_0 = 60.0 */ 1114636288L,\
/* Manual_Inj_torque_ki_0 = 3.250000238418579 */ 1078984705L,\
/* Manual_Inj_flux_kp_0 = 60.0 */ 1114636288L,\
/* Manual_Inj_flux_ki_0 = 3.250000238418579 */ 1078984705L,\
/* Manual_Inj_abs_speed_0 = 0.0 */ 0L,\
/* Manual_Inj_transition_time_0 = 0 */ 0L,\
/* Manual_Inj_torque_kp_1 = 0.0 */ 0L,\
/* Manual_Inj_torque_ki_1 = 0.0 */ 0L,\
/* Manual_Inj_flux_kp_1 = 0.0 */ 0L,\
/* Manual_Inj_flux_ki_1 = 0.0 */ 0L,\
/* Manual_Inj_abs_speed_1 = 0.0 */ 0L,\
/* Manual_Inj_transition_time_1 = 0 */ 0L,\
/* Manual_Inj_torque_kp_2 = 0.0 */ 0L,\
/* Manual_Inj_torque_ki_2 = 0.0 */ 0L,\
/* Manual_Inj_flux_kp_2 = 0.0 */ 0L,\
/* Manual_Inj_flux_ki_2 = 0.0 */ 0L,\
/* Manual_Inj_abs_speed_2 = 0.0 */ 0L,\
/* Manual_Inj_transition_time_2 = 0 */ 0L,\
/* Pwm_Speed_Threshold_InvComp = 200.0 */ 1128792064L,\
/* sizeof_Ld_Lq_Lut = 8 */ 8L,\
/* step_inv_L_Lut = 1.0 */ 1065353216L,\
/* Ld_input_0 = 0.0 */ 0L,\
/* Ld_output_0 = 0.048229001462459564 */ 1027967942L,\
/* Ld_input_1 = 1.0 */ 1065353216L,\
/* Ld_output_1 = 0.048229001462459564 */ 1027967942L,\
/* Ld_input_2 = 2.0 */ 1073741824L,\
/* Ld_output_2 = 0.048229001462459564 */ 1027967942L,\
/* Ld_input_3 = 3.0 */ 1077936128L,\
/* Ld_output_3 = 0.048229001462459564 */ 1027967942L,\
/* Ld_input_4 = 4.0 */ 1082130432L,\
/* Ld_output_4 = 0.04633500054478645 */ 1027459525L,\
/* Ld_input_5 = 5.0 */ 1084227584L,\
/* Ld_output_5 = 0.04439599812030792 */ 1026939028L,\
/* Ld_input_6 = 6.0 */ 1086324736L,\
/* Ld_output_6 = 0.04194300249218941 */ 1026280557L,\
/* Ld_input_7 = 7.0 */ 1088421888L,\
/* Ld_output_7 = 0.039986997842788696 */ 1025755496L,\
/* Lq_input_0 = 0.0 */ 0L,\
/* Lq_output_0 = 0.0487699992954731 */ 1028113165L,\
/* Lq_input_1 = 1.0 */ 1065353216L,\
/* Lq_output_1 = 0.04868299886584282 */ 1028089811L,\
/* Lq_input_2 = 2.0 */ 1073741824L,\
/* Lq_output_2 = 0.04859500005841255 */ 1028066189L,\
/* Lq_input_3 = 3.0 */ 1077936128L,\
/* Lq_output_3 = 0.048514001071453094 */ 1028044446L,\
/* Lq_input_4 = 4.0 */ 1082130432L,\
/* Lq_output_4 = 0.047520000487565994 */ 1027777621L,\
/* Lq_input_5 = 5.0 */ 1084227584L,\
/* Lq_output_5 = 0.04558100178837776 */ 1027257125L,\
/* Lq_input_6 = 6.0 */ 1086324736L,\
/* Lq_output_6 = 0.04312799870967865 */ 1026598652L,\
/* Lq_input_7 = 7.0 */ 1088421888L,\
/* Lq_output_7 = 0.04017199948430061 */ 1025805157L,\
/* Ldq_input_0 = 0.0 */ 0L,\
/* Ldq_output_0 = 0.0 */ 0L,\
/* Ldq_input_1 = 1.0 */ 1065353216L,\
/* Ldq_output_1 = 0.0 */ 0L,\
/* Ldq_input_2 = 2.0 */ 1073741824L,\
/* Ldq_output_2 = 0.0 */ 0L,\
/* Ldq_input_3 = 3.0 */ 1077936128L,\
/* Ldq_output_3 = 0.0 */ 0L,\
/* Ldq_input_4 = 4.0 */ 1082130432L,\
/* Ldq_output_4 = 0.0 */ 0L,\
/* Ldq_input_5 = 5.0 */ 1084227584L,\
/* Ldq_output_5 = 0.0 */ 0L,\
/* Ldq_input_6 = 6.0 */ 1086324736L,\
/* Ldq_output_6 = 0.0 */ 0L,\
/* Ldq_input_7 = 7.0 */ 1088421888L,\
/* Ldq_output_7 = 0.0 */ 0L,\
/* Max_Squared_Inv_Current = 40.96000289916992 */ 1109645067L,\
/* Max_Design_Motor_Torque = 26.0 */ 1104150528L,\
/* Rotor_Flux_Nominal = 0.17299999296665192 */ 1043408617L,\
/* Force_Default_Gains_Time = 1000 */ 1000L,\
/* Max_Cos = -0.25999999046325684 */ 3196395192L,\
/* Kp_load_angle = 30.0 */ 1106247680L,\
/* Ki_load_angle = 0.25 */ 1048576000L,\
/* kp_speed_0 = 6.493526935577393 */ 1087359737L,\
/* ki_speed_0 = 0.002685741987079382 */ 993002310L,\
/* speed_abs_speed_0 = 61.0 */ 1114898432L,\
/* transition_time_speed_0 = 20 */ 20L,\
/* kp_speed_1 = 5.729582786560059 */ 1085757630L,\
/* ki_speed_1 = 0.002136657014489174 */ 990644008L,\
/* speed_abs_speed_1 = 115.0 */ 1122369536L,\
/* transition_time_speed_1 = 20 */ 20L,\
/* kp_speed_2 = 4.631412982940674 */ 1083454601L,\
/* ki_speed_2 = 0.002082942286506295 */ 990413305L,\
/* speed_abs_speed_2 = 501.0 */ 1140490240L,\
/* transition_time_speed_2 = 20 */ 20L,\
/* kp_speed_3 = 1.100079894065857 */ 1066192747L,\
/* ki_speed_3 = 0.00027573617990128696 */ 965775535L,\
/* speed_abs_speed_3 = 1900.0 */ 1156415488L,\
/* transition_time_speed_3 = 20 */ 20L,\
/* Max_Braking_Current = 2.200000047683716 */ 1074580685L,\
/* Max_Braking_Torque = 10.0 */ 1092616192L,\
/* pole_pairs_factor = 27.0 */ 1104674816L,\
/* sizeof_MTPA_Lut = 16 */ 16L,\
/* step_inv_MTPA_Lut = 0.45892614126205444 */ 1055586398L,\
/* MTPA_Torque_0 = 1.440999984741211 */ 1069052592L,\
/* MTPA_Flux_0 = 0.17399999499320984 */ 1043475726L,\
/* MTPA_Torque_1 = 3.619999885559082 */ 1080536596L,\
/* MTPA_Flux_1 = 0.1770000010728836 */ 1043677053L,\
/* MTPA_Torque_2 = 5.798999786376953 */ 1085903208L,\
/* MTPA_Flux_2 = 0.18199999630451202 */ 1044012597L,\
/* MTPA_Torque_3 = 7.978000164031982 */ 1090472903L,\
/* MTPA_Flux_3 = 0.1899999976158142 */ 1044549468L,\
/* MTPA_Torque_4 = 10.156999588012695 */ 1092780818L,\
/* MTPA_Flux_4 = 0.20000000298023224 */ 1045220557L,\
/* MTPA_Torque_5 = 12.336000442504883 */ 1095065666L,\
/* MTPA_Flux_5 = 0.21199999749660492 */ 1046025863L,\
/* MTPA_Torque_6 = 14.515000343322754 */ 1097350513L,\
/* MTPA_Flux_6 = 0.22499999403953552 */ 1046898278L,\
/* MTPA_Torque_7 = 16.694000244140625 */ 1099271504L,\
/* MTPA_Flux_7 = 0.23999999463558197 */ 1047904911L,\
/* MTPA_Torque_8 = 18.87299919128418 */ 1100413927L,\
/* MTPA_Flux_8 = 0.2549999952316284 */ 1048743772L,\
/* MTPA_Torque_9 = 21.052000045776367 */ 1101556351L,\
/* MTPA_Flux_9 = 0.26600000262260437 */ 1049112871L,\
/* MTPA_Torque_10 = 23.231000900268555 */ 1102698775L,\
/* MTPA_Flux_10 = 0.2800000011920929 */ 1049582633L,\
/* MTPA_Torque_11 = 25.40999984741211 */ 1103841198L,\
/* MTPA_Flux_11 = 0.29499998688697815 */ 1050085949L,\
/* MTPA_Torque_12 = 27.589000701904297 */ 1104983622L,\
/* MTPA_Flux_12 = 0.30000001192092896 */ 1050253722L,\
/* MTPA_Torque_13 = 29.76799964904785 */ 1106126045L,\
/* MTPA_Flux_13 = 0.30000001192092896 */ 1050253722L,\
/* MTPA_Torque_14 = 31.94700050354004 */ 1107268469L,\
/* MTPA_Flux_14 = 0.30000001192092896 */ 1050253722L,\
/* MTPA_Torque_15 = 34.125999450683594 */ 1107853574L,\
/* MTPA_Flux_15 = 0.30000001192092896 */ 1050253722L,\
/* sizeof_MTPV_Lut = 16 */ 16L,\
/* step_inv_MTPV_Lut = 58.823524475097656 */ 1114327882L,\
/* MTPV_Flux_0 = 0.02199999988079071 */ 1018444120L,\
/* MTPV_Torque_0 = 2.2090001106262207 */ 1074618434L,\
/* MTPV_Flux_1 = 0.039000000804662704 */ 1025490551L,\
/* MTPV_Torque_1 = 3.9149999618530273 */ 1081773916L,\
/* MTPV_Flux_2 = 0.0560000017285347 */ 1030053954L,\
/* MTPV_Torque_2 = 5.625 */ 1085538304L,\
/* MTPV_Flux_3 = 0.0729999989271164 */ 1033208070L,\
/* MTPV_Torque_3 = 7.335999965667725 */ 1089126531L,\
/* MTPV_Flux_4 = 0.09000000357627869 */ 1035489772L,\
/* MTPV_Torque_4 = 9.041999816894531 */ 1091611656L,\
/* MTPV_Flux_5 = 0.10700000077486038 */ 1037771473L,\
/* MTPV_Torque_5 = 10.746999740600586 */ 1093399478L,\
/* MTPV_Flux_6 = 0.12399999797344208 */ 1040053174L,\
/* MTPV_Torque_6 = 12.45300006866455 */ 1095188349L,\
/* MTPV_Flux_7 = 0.14100000262260437 */ 1041261134L,\
/* MTPV_Torque_7 = 14.163999557495117 */ 1096982462L,\
/* MTPV_Flux_8 = 0.15800000727176666 */ 1042401985L,\
/* MTPV_Torque_8 = 15.87399959564209 */ 1098775527L,\
/* MTPV_Flux_9 = 0.17499999701976776 */ 1043542835L,\
/* MTPV_Torque_9 = 17.579999923706055 */ 1099736023L,\
/* MTPV_Flux_10 = 0.19200000166893005 */ 1044683686L,\
/* MTPV_Torque_10 = 19.28499984741211 */ 1100629934L,\
/* MTPV_Flux_11 = 0.20900000631809235 */ 1045824537L,\
/* MTPV_Torque_11 = 20.990999221801758 */ 1101524369L,\
/* MTPV_Flux_12 = 0.22599999606609344 */ 1046965387L,\
/* MTPV_Torque_12 = 22.702999114990234 */ 1102421950L,\
/* MTPV_Flux_13 = 0.24300000071525574 */ 1048106238L,\
/* MTPV_Torque_13 = 24.41200065612793 */ 1103317959L,\
/* MTPV_Flux_14 = 0.25999999046325684 */ 1048911544L,\
/* MTPV_Torque_14 = 26.118000030517578 */ 1104212394L,\
/* MTPV_Flux_15 = 0.2770000100135803 */ 1049481970L,\
/* MTPV_Torque_15 = 30.46339988708496 */ 1106490635L,\
/* sizeof_Rotor_Flux_Lut = 8 */ 8L,\
/* step_inv_Rotor_Flux_Lut = 1.0 */ 1065353216L,\
/* RotorFlux_input_0 = 1.0 */ 1065353216L,\
/* RotorFlux_output_0 = 0.17299999296665192 */ 1043408617L,\
/* RotorFlux_input_1 = 2.0 */ 1073741824L,\
/* RotorFlux_output_1 = 0.17299999296665192 */ 1043408617L,\
/* RotorFlux_input_2 = 3.0 */ 1077936128L,\
/* RotorFlux_output_2 = 0.17299999296665192 */ 1043408617L,\
/* RotorFlux_input_3 = 4.0 */ 1082130432L,\
/* RotorFlux_output_3 = 0.17299999296665192 */ 1043408617L,\
/* RotorFlux_input_4 = 5.0 */ 1084227584L,\
/* RotorFlux_output_4 = 0.16300000250339508 */ 1042737529L,\
/* RotorFlux_input_5 = 6.0 */ 1086324736L,\
/* RotorFlux_output_5 = 0.15299999713897705 */ 1042066440L,\
/* RotorFlux_input_6 = 7.0 */ 1088421888L,\
/* RotorFlux_output_6 = 0.15000000596046448 */ 1041865114L,\
/* RotorFlux_input_7 = 8.0 */ 1090519040L,\
/* RotorFlux_output_7 = 0.15000000596046448 */ 1041865114L,\
/*Current_Offset_Comp_Speed_Hyst_Thr = =Current Offset Comp Speed Thr hysteresis/100*/                     1028443341L,\
/*Current_Offset_Comp_Current_Thr = =Current Offset Comp Current Thr*/                     1068826100L,\
/*Current_Offset_Comp_Max_Current_Comp = =Current Offset Comp Max Current Compensation*/                     1028443341L,\
/*Current_Offset_Comp_Full_Cycle_Cnt = =Current Offset Comp Full Cycle Counter*/                     15L,\
/*Input Processing Dummy 1 = */                     0L,\
/*Input Processing Dummy 2 = */                     0L,\
/*Phase_Advance_Coeff = =Phase Advance Coefficient*/                     0L,\
/*Resistance_Adapt_Recovery = =Stator Resistance adaptation recovery*/                     950976884L,\
/*Swap Phase Time Threshold  = =Swap Phase Time Threshold /Observer call rate */                     8000L,\
/*Swap Phase Current Threshold  = =Swap Phase Current Threshold*/                     1083179008L,\
/*Swap Phase Speed  Threshold  = =Swap Phase Speed Threshold/60*2*pi()*/                     1054242640L,\
/*Pll_Engage_Speed_Thr = =PLL_Engage Speed Threshold /60*'PolePairs*2*pi()*/                     1089553978L,\
/*Pll_Engage_Speed_Err_Thr = =PLL_Engage Speed Error Threshold /60*'PolePairs*2*pi()*/                     1099413376L,\
/*Observer Dummy 1 = */                     0L,\
/*Observer Dummy 2 = */                     0L,\
/*Min_Braking_Diss_Torque_Low_Thr = =Min Braking Diss Torque Low Thr*/                     1064279474L,\
/*Min_Braking_Diss_Torque_High_Thr = =Min Braking Diss Torque High Thr*/                     1066779279L,\
/*Max_Braking_Gen_Low_Speed = =Max Braking Gen Low Speed*/                     1075167887L,\
/*Max_Braking_Gen_High_Speed = =Max Braking Gen High Speed*/                     0L,\
/*Max_Braking_Gen_Low_High_Speed_Thr = =Max Braking Gen Low/High Speed Threshold/60*2*pi()*/                     1099303570L,\
/*Braking_Resistance_Percentage = =Braking Resistance Percentage/100*/                     1064514355L,\
/*Braking_Mode = =Braking Mode */                     1L,\
/*Speed Regulator Dummy 1 = */                     0L,\
/*Speed Regulator Dummy 2 = */                     0L,\
/*Braking Mode = =Braking Mode */                     1L,\
/*Id_Braking_Prop_Gain = =Id Braking Prop Gain */                     1017370378L,\
/*Id_Braking_Step_Back = =Id Braking Step Back*/                     1028443341L,\
/*Overflux_Charging = =Overflux Charging*/                     981668463L,\
/*Overflux_Min_Perc = =Overflux min percentage*/                     0L,\
/*Flux_Adaptation_G_Gain = =Flux Adaptation G Gain *Observer call rate*/                     936490775L,\
/*Flux_Adaptation_Low_Limit = =(1-FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1039663943L,\
/*Flux_Adaptation_High_Limit = =(1+FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1046891568L,\
/*Dq Ref Dummy 1 = */                     0L,\
/*Dq Ref Dummy 2 = */                     0L,\
/*MAX_SPEED_RPM  = =MAX_SPEED_RPM */                     2000L,\
/*MIN_SPEED_RPM  = =MIN_SPEED_RPM */                     10L,\
/*MAX_RPM_PER_SEC_ACCEL  = =MAX_RPM_PER_SEC_ACCEL */                     85L,\
/*MAX_RPM_PER_SEC_DECEL  = =MAX_RPM_PER_SEC_DECEL */                     50L,\
/*MIN_RPM_PER_SEC_ACCEL = =MIN_RPM_PER_SEC_ACCEL*/                     1L,\
/*MIN_RPM_PER_SEC_DECEL = =MIN_RPM_PER_SEC_DECEL*/                     1L,\
};


#endif

#endif //MCL_COMPLETE_DD_PRM_H
