/**
 *  @file        Mcl_Additional_sBPM_prm.h
 *  @brief       DTC Loop Parameters for 3-phase motors.
 *
 *               ==== AUTOMATIC GENERATED FILE! DO NOT TOUCH IT, USE EXCEL MACRO! ====
 *
 *  @details     This module defines all parameters of the DTC control loop for 3-phase motors. Created in 10/3/2022 9:58 
 *               Setting File Parameters for sBPM Hefei H27
 *               Generated from https://docs.google.com/spreadsheets/d/14APUdvp52lCmj9AYKxURuVH76wF0RGPDxWy2RUyRW88/edit
 *               Generated by luigi_fagnano@whirlpool.com
 *  @copyright   Copyright 2022.  Whirlpool Corporation.  All rights reserved - CONFIDENTIAL
 *
 */

#ifndef MCL_ADDITIONAL_SBPM_PRM_H
#define MCL_ADDITIONAL_SBPM_PRM_H


//=====================================================================================================================
//-------------------------------------- PUBLIC (Extern Variables, Constants & Defines) -------------------------------
//=====================================================================================================================


#include "MciParametersLoader_prv.h"


//DTC Phisical Motor Control Parameters

//0.1
//Stator Resistance = 2.87 Ohm
//Rotor flux  = 0.0845 Wb
//Maximum electromagnetic torque = 4 Nm

//Pole pairs
//Current Offset Comp Speed Thr (0 to disable) = 0 rpm
//Current Offset Comp Speed Thr hysteresis = 0 %
//Current Offset Comp Current Thr = 0 A
//Current Offset Comp Max Current Compensation = 0 A
//Current Offset Comp Full Cycle Counter = 0 na

//Hardware (inverter) configuration
//Maximum peak phase current = 6 A

//Observer Parameters
//Stator Resistance adaptation limits = 15 %
//Stator Resistance adaptation gain = 160 Ohm/(Wb*s)
//Stator Resistance adaptation recovery = 83.33 Ohm*us
//Current threshold to enable resistance adaptation = 4.5 A
//Speed threshold to enable resistance adaptation = 40 rpm
//Observer G gain = 60 V/Wb
//Observer Integ G gain = 1000 V/Wb/s
//Observer Integ Limits = 0.5 V
//Observer Integ activation speed threshold = 400 rpm
//Stator Resistance adaptation offset = 0 Ohm
//Phase Advance Coefficient (0 to disable) = 0 NA
//Starting time threshold = 0.5 s
//PLL - Kp gain = 118 1/s
//PLL - Ki gain = 3410 Stat
//PLL - Engage Speed Threshold  = 40 rpm
//PLL - Engage Speed Error Threshold  = 40 rpm
//Observer call rate (sampling time) = 0.000125 s
//Swap Phase Time Threshold (0 to disable) = 0 s
//Swap Phase Current Threshold = 4.5 A
//Swap Phase Speed Threshold = 40 rpm

//Speed Controller Parameters
//Maximum cosine of load angle = -0.26 NA
//Load angle controller Kp = 0 Nm
//Load angle controller Ki = 8000 Nm/s
//Time to force the use of default gains = 1 s
//Default Acceleration = 75 rpm/s
//Min Speed Default Acceleration = 15 rpm
//Max Braking Diss Torque = 1 Nm
//Max Braking  Diss Current = 3.38 A
//Min Braking Diss Torque Low Thr = 0.08 Nm
//Min Braking Diss Torque High Thr = 0.1 Nm
//Max Braking Gen Low Speed = 0.2 Nm
//Max Braking Gen High Speed = 0 Nm
//Max Braking Gen Low/High Speed Threshold = 1900 rpm
//Braking Resistance Percentage = 95 %
//Id Braking Prop Gain  = 0.02 A/ms
//Id Braking Step Back = 0.05 A
//Braking Mode (0 = conservative) = 0 NA

//DQ Reference Generator Parameters
//Starting time = 1 s
//Maximum designed flux  = 0.2 Wb
//Speed threshold to enable/disable overflux = 375 rpm
//Percentage to be applied of overflux = 10 %
//Overflux decrement = 0.0001 Wb
//Overflux Charging = 0.1 %
//Overflux min percentage = 0 %
//Flux Adaptation G Gain (0 to disable) = 0.2 Wb/(A*Ts)
//FLux Adaptation Hysteresis Percentage = 30 %
//K (torque error compensation) = 0.58 1/Nm
//Torque error compensation saturation = 0.5 NA
//Max Modulation Index(REF) = 98 %

//DQ Controllers Parameters
//Starting time to force gains = 1 s
//Phase advance coefficient = 1 NA
//Max Modulation Index (CTRL) = 115 %
//Pi Volt Margin for Vd_Max = 140 V
//Absolute speed threshold range - region[0] = 1905 rpm
//Absolute speed threshold range - region[1] = 14000 rpm
//Absolute speed threshold range - region[2] = 20000 rpm
//Torque controller Kp - region [0] = 10 V/Nm
//Torque controller Ki - region [0] = 2000 V/(Nm*s)
//Torque controller Kp - region [1] = 150 V/Nm
//Torque controller Ki - region [1] = 12000 V/(Nm*s)
//Torque controller Kp - region [2] = 150 V/Nm
//Torque controller Ki - region [2] = 12000 V/(Nm*s)
//Flux controller Kp - region [0] = 150 V/Wb
//Flux controller Ki - region [0] = 15000 V/(Wb*s)
//Flux controller Kp - region [1] = 8000 V/Wb
//Flux controller Ki - region [1] = 900000 V/(Wb*s)
//Flux controller Kp - region [2] = 8000 V/Wb
//Flux controller Ki - region [2] = 900000 V/(Wb*s)
//Time  to switch gains - region[0] = 2 s
//Time  to switch gains - region[1] = 3 s
//Time  to switch gains - region[2] = 3 s

//Pwm Parameters
//Speed threshold to disable compensation (applied 5% hysteresis) = 6000 rpm

//Running algorithm
//Minimum speed (guard condition) to enter stopping = 228 rpm
//Minimum speed to switch off all IGBTs = 684 rpm
//Debouncer of running finished check = 5 NA
//Time to set all devices off below minimum speed = 1.8 s
//Time threshold for locked rotor at startup or in running = 4 s
//Starting debounce time to run with torque at its maximum = 3 s
//Running debounce time to run with torque at its maximum = 10 s
//Max Current for detecting locked rotor (% of max current) = 0.95 %

//Manual injection
//d current (Flux) controller Kp = 200 V/A
//d current (Flux) controller Ki = 80000 V/A/s
//q current (Torque) controller Kp = 200 V/A
//q current (Torque) controller Ki = 80000 V/A/s

//Resistance estimation algorithm
//Estimation timeout = 4 s
//Current level - 1st plateau = 4 A
//Current level - 2nd plateau = 5 A
//Current level - 3rd plateau = 1 A
//Time of 1st plateau = 0.6 s
//Time of 2nd plateau = 0.6 s
//Time of 3rd plateau = 0.4 s
//Voltage step for 1st plateau = 0.078125 V
//Voltage step for 2nd plateau = 0.078125 V
//Voltage step for 3nd plateau = 0.078125 V
//Oscillation check timer = 0.1 s
//Minimum number of samples to average = 300 NA
//Oscillation speed threshold = 30 rpm
//Time to reset resistance (declare resistance as outdated) = 6 min
//Resistance estimation call rate (sampling time) = 0.001 s
//Resistance estimation handler rate (sampling time) = 0.000125 s
//Spin speed to trigger resistance on next start up = 1710 rpm
//Time between measurement after reset = 1 min
//Number of estimation after reset = 3 NA
//Time between measurement under normal operation = 5 min
//Number of estimation in a row after spin = 3 NA
//Phase resistance calibrated at temperature = #REF! Ohm
//Temperature coefficient = 232.1 °C/Ohm
//Base temperature = 25 °C
//Samples Number = 1024 NA

//MCI PARAMETERS
//MAX_SPEED_RPM  = 19800 rpm
//MIN_SPEED_RPM  = 100 rpm
//MAX_RPM_PER_SEC_ACCEL  = 4000 rpm/s
//MAX_RPM_PER_SEC_DECEL  = 4000 rpm/s
//MIN_RPM_PER_SEC_ACCEL = 1 rpm/s
//MIN_RPM_PER_SEC_DECEL = 1 rpm/s




signed long int Mcl_Additional_Params_sBPM_SF[40] =
{
/*Current_Offset_Comp_Speed_Hyst_Thr = =Current Offset Comp Speed Thr hysteresis/100*/                     0L,\
/*Current_Offset_Comp_Current_Thr = =Current Offset Comp Current Thr*/                     0L,\
/*Current_Offset_Comp_Max_Current_Comp = =Current Offset Comp Max Current Compensation*/                     0L,\
/*Current_Offset_Comp_Full_Cycle_Cnt = =Current Offset Comp Full Cycle Counter*/                     0L,\
/*Input Processing Dummy 1 = */                     0L,\
/*Input Processing Dummy 2 = */                     0L,\
/*Phase_Advance_Coeff = =Phase Advance Coefficient*/                     0L,\
/*Resistance_Adapt_Recovery = =Stator Resistance adaptation recovery*/                     950976884L,\
/*Swap Phase Time Threshold  = =Swap Phase Time Threshold /Observer call rate */                     0L,\
/*Swap Phase Current Threshold  = =Swap Phase Current Threshold*/                     1083179008L,\
/*Swap Phase Speed  Threshold  = =Swap Phase Speed Threshold/60*2*pi()*/                     1082526354L,\
/*Pll_Engage_Speed_Thr = =PLL_Engage Speed Threshold /60*'PolePairs*2*pi()*/                     1099303570L,\
/*Pll_Engage_Speed_Err_Thr = =PLL_Engage Speed Error Threshold /60*'PolePairs*2*pi()*/                     1099303570L,\
/*Observer Dummy 1 = */                     0L,\
/*Observer Dummy 2 = */                     0L,\
/*Min_Braking_Diss_Torque_Low_Thr = =Min Braking Diss Torque Low Thr*/                     1034147594L,\
/*Min_Braking_Diss_Torque_High_Thr = =Min Braking Diss Torque High Thr*/                     1036831949L,\
/*Max_Braking_Gen_Low_Speed = =Max Braking Gen Low Speed*/                     1045220557L,\
/*Max_Braking_Gen_High_Speed = =Max Braking Gen High Speed*/                     0L,\
/*Max_Braking_Gen_Low_High_Speed_Thr = =Max Braking Gen Low/High Speed Threshold/60*2*pi()*/                     1128724400L,\
/*Braking_Resistance_Percentage = =Braking Resistance Percentage/100*/                     1064514355L,\
/*Braking_Mode = =Braking Mode */                     0L,\
/*Speed Regulator Dummy 1 = */                     0L,\
/*Speed Regulator Dummy 2 = */                     0L,\
/*Braking Mode = =Braking Mode */                     0L,\
/*Id_Braking_Prop_Gain = =Id Braking Prop Gain */                     1017370378L,\
/*Id_Braking_Step_Back = =Id Braking Step Back*/                     1028443341L,\
/*Overflux_Charging = =Overflux Charging*/                     981668463L,\
/*Overflux_Min_Perc = =Overflux min percentage*/                     0L,\
/*Flux_Adaptation_G_Gain = =Flux Adaptation G Gain *Observer call rate*/                     936490775L,\
/*Flux_Adaptation_Low_Limit = =(1-FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1030899525L,\
/*Flux_Adaptation_High_Limit = =(1+FLux Adaptation Hysteresis Percentage/100)*Rotor flux */                     1038153993L,\
/*Dq Ref Dummy 1 = */                     0L,\
/*Dq Ref Dummy 2 = */                     0L,\
/*MAX_SPEED_RPM  = =MAX_SPEED_RPM */                     19800L,\
/*MIN_SPEED_RPM  = =MIN_SPEED_RPM */                     100L,\
/*MAX_RPM_PER_SEC_ACCEL  = =MAX_RPM_PER_SEC_ACCEL */                     4000L,\
/*MAX_RPM_PER_SEC_DECEL  = =MAX_RPM_PER_SEC_DECEL */                     4000L,\
/*MIN_RPM_PER_SEC_ACCEL = =MIN_RPM_PER_SEC_ACCEL*/                     1L,\
/*MIN_RPM_PER_SEC_DECEL = =MIN_RPM_PER_SEC_DECEL*/                     1L,\
};


#endif //MCL_ADDITIONAL_SBPM_PRM_H
